BlueBrain/CoreNeuron

- coreneuron/nrnconf.h
- coreneuron/nrniv/global_vars.cpp
- coreneuron/nrniv/mk_mech.cpp
- coreneuron/nrniv/nrn_datareader.cpp
- coreneuron/nrniv/nrn_setup.cpp
- coreneuron/nrnoc/nrnoc_aux.c
This is related to NEURON [PR#28](https://github.com/nrnhines/nrn/pull/28).
> Check input dataset version string from input datasets

- coreneuron/nrniv/cellorder.cpp
- coreneuron/nrniv/cellorder.h
- tests/unit/interleave_info/CMakeLists.txt
- tests/unit/interleave_info/check_constructors.cpp
Probably InterleaveInfo won't be used in other contexts but this addresses seggestions in #3 (rule of 3).
> Implement copy constructor and assignment operator for InterleaveInfo

- CMake/config/SetRpath.cmake
> update RPath config for Cray (static linkage) 

- coreneuron/kinderiv.py
- coreneuron/mech/mod2c_core_thread.h
- coreneuron/scopmath_core/dimplic.c
- updated kinderiv.py to generate
- added euler_thread from neuron and updated for aos/soa layout
@nrnhines : could you check if below changes belong to `dimplic.c` ? At least I tested the functionality/ results with plasticity model of Giuseppe and produces same results as NEURON+Neurodamus.
> Added support for euler (similar to thread safe support in NEURON)

- coreneuron/utils/reports/nrnreport.cpp
(to be consistent woth neurodamus)
Update mod2c to latest master
> Start reporting/recording of reports from t = 0

- coreneuron/mech/mod2c_core_thread.h
- coreneuron/nrniv/nrniv_decl.h
- coreneuron/nrnoc/register_mech.c
- coreneuron/scopmath_core/sparse_thread.c
We centralize all declarations needed by mod2c in coreneuron headers
> Trying to centralize includes and extern declaration visible to mod2c

- coreneuron/nrniv/netpar.cpp
- coreneuron/nrnmpi/mpispike.cpp
- coreneuron/nrnmpi/nrnmpidec.h
Also remove superfluous mpi wrapper function
> Use the value calculated mindelay by the MPI min reduction

- CMakeLists.txt
- README.md
- coreneuron/CMakeLists.txt
- coreneuron/mech/mod2c_core_thread.h
- coreneuron/utils/randoms/nrnran123.cpp
- acc routine seq in header causes pgi internal errors
- sm_20 is outdated, keep minimum sm_35
> Minor changes to compile with OpenACC and latest cuda + pgi compiler:

- coreneuron/utils/reports/nrnreport.cpp
- coreneuron/utils/reports/nrnreport.h
- coreneuron/utils/reports/report_configuration_parser.cpp
- replace MAX_REPORT_PATH_LEN with MAX_FILEPATH_LEN
- fixes segfault with long filepath
> Replace report_name with report_path

- coreneuron/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/jenkins/Jenkinsfile
- tests/jenkins/install.sh
- tests/jenkins/nrnivmodl-core.sh
- tests/jenkins/nrnivmodl.sh
- tests/jenkins/ringtest.sh
- tests/jenkins/run_corenrn.sh
- tests/jenkins/run_neuron.sh
- Uses Jenkinsfile found in /tests/jenkins
- Builds AoS and SoA configuration of CoreNeuron
- Tests simple ringtest with both of them
- Clones master branch of https://github.com/pramodk/testcorenrn
to load more tests
- Uses scripts found in /tests/jenkins directory to run all tests
> Created Jenkins pipeline for CoreNeuron

- CMake/packages/Findnmodl.cmake
- CMakeLists.txt
- add pythonpath for nmodl
- fix include directory finding
> Some minor fixes that I missed in the last PR

- extra/nrnivmodl-core
After discussing with @ferdonline we decided to for now continue generating the `install` script to keep the same functionality of building and installing with the same options. Instead we've added some more code comments describing what is being done and how the code could be changed to be improved.
> Fixed path in nrnivmodl-core script and improved code documentaiton

- .travis.yml
- coreneuron/CMakeLists.txt
- coreneuron/nrnoc/nrnoc_ml.ispc
> Issue #41 : travis CI configuration

- extra/nrnivmodl-core.in
- tests/jenkins/nrnivmodl-core.sh
MODS_LOCATION was always being overwritten from CLI. Now it can be
loaded from the save file.
Check if provided mods directory exists
> Small fixes in nrnivmodl regarding MODS_LOCATION

- coreneuron/sim/fadvance_core.cpp
- coreneuron/sim/multicore.cpp
- coreneuron/sim/multicore.hpp
It let us reduce global variable for keeping state
> make nrn_multithread_job accept arguments

- CMakeLists.txt
> Add --pic as default flag for ISPC compilation

- CMakeLists.txt
Bugfix issue #285 with nmodl [issue 201](https://github.com/BlueBrain/nmodl/issues/201) solution
> Disable vectorize in eigen in nmodl when gpu is enabled

- CMakeLists.txt
- extra/nrnivmodl_core_makefile.in
> Avoid hardcoded python binary path

- extra/CMakeLists.txt
- Random123 submodule update with PGI on Power9
- Remove linking of imported target Threads::Thread
> Fixed for building on IBM Power 9 with GPU Support

- coreneuron/io/reports/report_event.hpp
- coreneuron/sim/fadvance_core.cpp
> Flush reports when having gap junctions

- coreneuron/mechanism/eion.cpp
See https://github.com/neuronsimulator/nrn/pull/685
> Fix for ion style error from NEURON

- coreneuron/mechanism/membfunc.hpp
- coreneuron/mechanism/nrnoc_ml.ispc
- coreneuron/network/cvodestb.cpp
- Fixes https://github.com/BlueBrain/CoreNeuron/issues/402
> Move at_time inside coreneuron namespace and redefine at_time in ispc

- extra/nrnivmodl_core_makefile.in
The makefile syntax was not clear to me. This version should work
> Fix default nmodl flags

- extra/nrnivmodl_core_makefile.in
> Folders: x86_64/core -> x86_64/corenrn

- CMake/CMakeTestISPCCompiler.cmake
> Fix cmake to find ispc compiler

- coreneuron/gpu/nrn_acc_manager.cpp
- coreneuron/io/global_vars.cpp
- coreneuron/io/nrn_checkpoint.hpp
- coreneuron/io/nrn_filehandler.hpp
- coreneuron/io/nrnsection_mapping.hpp
- coreneuron/mechanism/mech/mod2c_core_thread.hpp
- coreneuron/mechanism/mech/modfile/pattern.mod
- coreneuron/mechanism/mech_mapping.cpp
- coreneuron/mechanism/mech_mapping.hpp
- coreneuron/mechanism/mechanism.hpp
- coreneuron/mechanism/membfunc.hpp
- coreneuron/mechanism/patternstim.cpp
- coreneuron/mechanism/register_mech.cpp
- coreneuron/network/multisend.cpp
- coreneuron/network/netcvode.cpp
- coreneuron/network/partrans.hpp
- coreneuron/network/tnode.hpp
- coreneuron/network/tqueue.hpp
- coreneuron/nrnconf.h
- coreneuron/permute/cellorder1.cpp
- coreneuron/permute/cellorder2.cpp
- coreneuron/utils/ivocvect.hpp
- coreneuron/utils/lpt.cpp
> Clean code for #250

- coreneuron/io/reports/report_handler.cpp
> Refactor reporting

- .github/workflows/coreneuron-ci.yml
> CoreNEURON CI via Github Actions

- coreneuron/apps/main1.cpp
- coreneuron/io/reports/binary_report_handler.cpp
- coreneuron/io/reports/nrnreport.hpp
- coreneuron/io/reports/report_configuration_parser.cpp
- coreneuron/io/reports/report_handler.cpp
- coreneuron/io/reports/sonata_report_handler.cpp
> Refactor reporting config file reading

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Added templates for PRs and new Issues
The only way to test those additions is to merge and test them I believe.
- GitHub
> Update issue and PR templates

- coreneuron/io/reports/report_handler.cpp
**Related ticket**
https://bbpteam.epfl.ch/project/issues/browse/CNEUR-364
> Report middle segment for soma reports

- CMake/MakefileBuildOptions.cmake
- coreneuron/CMakeLists.txt
- tests/jenkins/install_coreneuron.sh
* mod2c now aborts when mod files is not threadsafe
* this avoids confusing compilation errors for end users
> Update mod2c to latest module

- coreneuron/network/multisend.cpp
- coreneuron/network/netcvode.cpp
- coreneuron/network/netcvode.hpp
- coreneuron/network/tqueue.cpp
- coreneuron/network/tqueue.hpp
- tests/unit/queueing/test_queueing.cpp
> Clean code

- .github/workflows/coreneuron-ci.yml
> Build release branches

- .github/workflows/coreneuron-ci.yml
- coreneuron/io/reports/report_handler.cpp
Assert was failing when synapse_id == 0
> Fix issue when passing synapse_id to the reporting

- .readthedocs.yml
- docs/conda_environment.yml
- docs/conf.py
> Publish documentation on ReadTheDocs

- coreneuron/mechanism/mech/modfile/netstim.mod
- coreneuron/utils/randoms/nrnran123.cpp
- coreneuron/utils/randoms/nrnran123.cu
- coreneuron/utils/randoms/nrnran123.h
-  related to neuronsimulator/nrn#373
> nrnran123.h `which` -> match neuron signature

- .github/workflows/coreneuron-ci.yml
> temporarily call brew update to unblock the CI

- README.md
> Update CoreNEURON build and testing documentation

- coreneuron/io/nrn_setup.cpp
- coreneuron/io/reports/nrnreport.hpp
- coreneuron/io/reports/report_configuration_parser.cpp
- coreneuron/io/reports/report_event.cpp
- coreneuron/io/reports/report_event.hpp
- coreneuron/io/reports/report_handler.cpp
- coreneuron/io/reports/report_handler.hpp
- coreneuron/sim/multicore.hpp
Add support for summation reports.
> Summation reports

- .github/workflows/coreneuron-ci.yml
- .github/workflows/coverage.yml
More over split github action in 2 parts (CI and coverage)
> Remove external sources from coverage

- coreneuron/utils/memory_utils.cpp
> change mallinfo to mallinfo2

- coreneuron/io/phase2.cpp
- coreneuron/io/phase2.hpp
- coreneuron/sim/multicore.cpp
- coreneuron/sim/multicore.hpp
Move Phase2::create_tml to coreneuron/sim/multicore
> Move Phase2::create_tml to coreneuron/sim/multicore

- coreneuron/network/tnode.hpp
- coreneuron/permute/balance.cpp
- coreneuron/permute/cellorder.cpp
- coreneuron/permute/cellorder.hpp
- coreneuron/permute/cellorder1.cpp
- coreneuron/permute/cellorder2.cpp
Cell permutation documentation
> Cell permutation documentation

- coreneuron/apps/main1.cpp
- coreneuron/io/nrn_checkpoint.cpp
- coreneuron/io/nrn_checkpoint.hpp
- coreneuron/io/nrn_filehandler.hpp
- coreneuron/io/nrn_setup.cpp
- coreneuron/io/nrn_setup.hpp
- coreneuron/io/phase2.cpp
- coreneuron/io/user_params.hpp
- coreneuron/mechanism/mech/enginemech.cpp
- coreneuron/nrniv/nrniv_decl.h
* make it as a class now
* remove most of global variables, but not all
* test for bbcore_write available is now at a better place
* the object is available inside  UserParams
* Remove unused FileHandlerWrap
> Refactor nrn_checkpoint

- .gitlab-ci.yml
Supersede #576 
Apply patch mentioned in https://github.com/neuronsimulator/nrn/pull/1261#issuecomment-866811604
> Enable CoreNEURON CI with NMODL

- coreneuron/io/reports/binary_report_handler.cpp
- coreneuron/io/reports/binary_report_handler.hpp
- coreneuron/io/reports/nrnreport.hpp
- coreneuron/io/reports/report_configuration_parser.cpp
- coreneuron/io/reports/report_event.cpp
- coreneuron/io/reports/report_event.hpp
- coreneuron/io/reports/report_handler.cpp
- coreneuron/io/reports/report_handler.hpp
- coreneuron/io/reports/sonata_report_handler.cpp
- coreneuron/io/reports/sonata_report_handler.hpp
- tests/jenkins/install_coreneuron.sh
Add support for soma and section targets when using summation reports.
CI_BRANCHES:NEURODAMUS_CORE_BRANCH=sandbox/jblanco/section_target,PYNEURODAMUS_BRANCH=sandbox/jblanco/section_target,
> Summation reports on soma, compartment and section targets

- .gitlab-ci.yml
- CMakeLists.txt
- README.md
- coreneuron/CMakeLists.txt
Include Eigen API from NMODL : Eigen OpenACC compatibility issues
CI_BRANCHES:SPACK_BRANCH=pramodk/eigen-bbp-version,
> Include Eigen API from NMODL : Eigen OpenACC compatibility issues

- CMakeLists.txt
- tests/jenkins/ringtest.sh
> Compile CUDA/OpenACC code for CC 80 as well (Ampere & Turing)

- .gitlab-ci.yml
Closes #665.
CI_BRANCHES:SPACK_BRANCH=magkanar/neuron_tests,NEURON_BRANCH=magkanar/olfactory_test,
> Added model_tests spack variable in the gitlab tests

- AUTHORS.txt
Add file listing code contributors, including those involved with discussions who may not have edited code
> Add AUTHORS.txt file to conform to software catalog guidelines

- coreneuron/apps/main1.cpp
- coreneuron/network/partrans.cpp
- coreneuron/network/partrans.hpp
> Add a function to delete gap indices from device

- README.md
- Add note for running GPU build with `NEURON` executable
- Related to https://github.com/BlueBrain/CoreNeuron/issues/742
```bash
module load cmake hpe-mpi gcc nvhpc/21.2 cuda/11.0.2 python-dev
cmake .. \
-DNRN_ENABLE_CORENEURON=ON \
-DCORENRN_ENABLE_GPU=ON \
-DNRN_ENABLE_INTERVIEWS=OFF \
-DNRN_ENABLE_RX3D=OFF \
-DCMAKE_INSTALL_PREFIX=./install \
-DPYTHON_EXECUTABLE=$(which python3) \
-DCMAKE_C_COMPILER=nvc \
-DCMAKE_CXX_COMPILER=nvc++ \
-DCMAKE_CUDA_COMPILER=nvcc /
cmake --build . --parallel 40 --target install
cd install
./bin/nrnivmodl -coreneuron mod
./x86_64/special test.py
```
- OS: RedHat
- Compiler: NVHPC 21.2
- Backend: GPU
> Update README.md with GPU instructions

- tests/jenkins/_env_setup.sh
- tests/jenkins/install_coreneuron.sh
- tests/jenkins/nrnivmodl-core.sh
- tests/jenkins/ringtest.sh
- tests/jenkins/run_corenrn.sh
- tests/jenkins/run_corenrn_restore.sh
- tests/jenkins/run_neuron_direct.sh
- tests/jenkins/spack_setup.sh
> Change spack setup paths to new 2022 deployment for Jenkins pipeline

- README.md
Add explanation of what is running to help users that don't touch / configure CI often
> Add some explanations of CI in README

- coreneuron/mechanism/membfunc.hpp
Fixes #746
Related to neuronsimulator/nrn#1581 and neuronsimulator/testcorenrn#8
** TODO **
> mod2c translated mod files with BEFORE/AFTER need a declaration.

- .gitlab-ci.yml
- CMakeLists.txt
Enable report in coverage to have more coverage on this side
> Always enable report in gitlab tests

- .github/workflows/test-as-submodule.yml
Avoid this failure: https://github.com/BlueBrain/CoreNeuron/runs/5271565952.
> test-as-submodule: ubuntu: apt-get update.

- .gitlab-ci.yml
This is a technical change that improves testing of the gitlab-pipelines helpers.
> Compatibility with GitLab CI helpers.

- CMake/config/CompilerFlagsHelpers.cmake
- coreneuron/CMakeLists.txt
* https://en.cppreference.com/w/cpp/filesystem#Notes
* Revert "CLI11 & GCC8 combo have special consideration  #839"
* This reverts commit 3a274647a7cd96fc6f1538096a69aa6b01fcdfad.
> Check if we need to link against stdc++fs

- coreneuron/io/output_spikes.cpp
* Change datatype from the number of spikes and buffer size to unsigned long
* Change unsigned long for size_t
CI_BRANCHES:NEURON_BRANCH=release/8.2
> Change num_spikes datatype to unsigned long (#878)

- .github/workflows/coreneuron-ci.yml
> GH actions updates following recent deprecation

- .github/workflows/test-as-submodule.yml
> NRN submodule CI: install pytest(cov) via pip
