BlueBrain/CoreNeuron

coreneuron/CMakeLists.txt

- Provide meaningful CMake error message when multiple mod
files with same name found in the mechanism search directory
- halfgap.mod file is added to the target if it is not found in
search directories (e.g. ringtest repo has halfgap.mod)
Recently user has reported an issue where CMake provide following error:
```
CMake Error: Attempt to add a custom rule to output "/homeb/pra095/pra09501/coreneuron_tutorial/sources/ringtest/coreneuron_x86/coreneuron/halfgap.c.rule" which already has a custom rule.
```
For the gap junction test I have added `halfgap.mod` in the coreneuron test directory. But if user provide `-DADDITIONAL_MECHPATH="/path/"` with another `halfgap.mod` then there will be above error message. These CMake error messages are not understandable for end users.
This PR add check …

CMake update for better error reporting for multiple mod files with same filename

---

CMake/portability/BlueGenePortability.cmake
CMakeLists.txt

CMake try to enable bg-q related memory usage functions on OS X while profiling with TAU.
Check spi.h on bg-q only

Fix issue with Tau instrumentation on OS X

---

CMakeLists.txt

CheckIncludeFiles was included and hence bg-q builds were failing.

fix bg-q build failure from #37

---

coreneuron/nrniv/main1.cpp

This was caught when trying to report and resulted in deadlock when ENABLE_REPORTS
Was infinte loop where events were requeued with 0 delay
JGK

Fix command line args which were taken as ints rather than doubles

---

coreneuron/nrniv/nrn_setup.cpp

This pull request fixes nrnhines/nrn#42.
The issue appeared when calling `nrnbbcore_write` from NEURON to generate a dataset for CoreNeuron. Specifically, the culprit of the issue appeared when NetCons without a target were present in the original python or hoc script that specified the model.
NetCons without a target were being (correctly) saved to the coreneuron dataset by NEURON. 
Moreover, _every NetCon has at least one weight_. 
NetCons without a target have a `pnttype` value of `0`.
However, when CoreNeuron was reading the same dataset, it was not increasing the value of `iw` because `pnt_receive_size[0]` is equal to `0`.
NetCons without a target are still being (correctly) saved to the coreneuron dataset by NEURON. 
NetCons without a target still have a `pnttype` value of `0`. …

Fixes nrnhines/nrn#42

---

coreneuron/nrnoc/multicore.c

When SoA layout is enabled with padding, the _check_table_thread
function expects padded nodecount. We were using non-padded nodecount
which was working with : AoS layout / without padding / when variables
were GLOBAL. This issue was discovered in latest StochKv where some
variables used in TABLE statement were changed from GLOBAL to RANGE.

Fix nodecount argument for check_table_thread

---

coreneuron/nrniv/nrn_acc_manager.cpp

Avoid dereferencing gpu pointer on CPU (this was
introduced from changes in #14).

Fix bug in gpu implementation (fixes #61)

---

coreneuron/nrniv/main1.cpp
coreneuron/nrniv/patternstim.cpp

- pattern.mod expects spike raster to be sorted (to avoid injecting
large events at the begining of simulation itself). Refactor
patternstim implementation to sort spike raster
- if rank is empty then don't create patternstim (avoid segfault)
- prcellstate file name time format changed simular to NEURON

Fix issues with spike replay / patternstim

---

coreneuron/nrniv/netcvode.cpp
coreneuron/nrniv/netpar.cpp
coreneuron/nrniv/nrn_filehandler.cpp
coreneuron/nrniv/nrn_stats.cpp
coreneuron/nrniv/nrnoptarg.cpp
coreneuron/nrniv/profiler_interface.cpp
coreneuron/nrnoc/eion.c
coreneuron/nrnoc/fadvance_core.c
coreneuron/nrnoc/multicore.c
coreneuron/nrnoc/nrnoc_aux.c
coreneuron/nrnoc/register_mech.c
coreneuron/utils/reports/nrnreport.cpp
coreneuron/utils/reports/nrnreport.h

in perspective of making coreneuron as a library, we need to be careful of potential symbol conflicts with Neuron.
This first step clean up potentially conflictual declarations.

Centralize global variables definitions

---

coreneuron/nrnoc/register_mech.c
coreneuron/scopmath_core/sparse_thread.c

* We enforce explicit casts: C is more tolerant than C++ on casts.
* We change variable names from C++ keywords into none conflicting names.
* explicit return type and arguments in declaration mandatory in C++

enforce c++ rules before migration

---

coreneuron/CMakeLists.txt
coreneuron/utils/randoms/nrnran123.c
coreneuron/utils/randoms/nrnran123.cu
coreneuron/utils/randoms/nrnran123.h

OpenACC resulting in nrnran123_set_globalindex call for gpu device
kerbel. This was resulting in failure and hence abnormal program
termination.

Bug fix in gpu implementation : global_vars.cpp was compiled with

---

coreneuron/nrnoc/fadvance_core.c
coreneuron/utils/progressbar/progressbar.c
coreneuron/utils/progressbar/progressbar.h

Add ETA while execution of psolve, fixes #86

---

coreneuron/utils/reports/nrnsection_mapping.h

runtime error while linking with neuron as library.

Add coreneuron namespace to report header to avoid

---

coreneuron/utils/randoms/Random123/features/compilerfeatures.h
coreneuron/utils/randoms/Random123/features/gccfeatures.h
coreneuron/utils/randoms/nrnran123.h

bgclang defines a new constant `__bgclang__`, which has to be used instead
of `__clang__`. Additionally we use a known workaround for BG\Q for
Random123 reported elsewhere.
just for completeness: https://lists.alcf.anl.gov/pipermail/llvm-bgq-discuss/2017-January/000679.html

Changes to Random123 to support bgclang

---

CMake/config/DeclareMod2CSubModule.cmake
CMakeLists.txt
coreneuron/CMakeLists.txt

Remove CMAKE_CACHE_ARGS to avoid long warnings like:
```
CMake Warning at /usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/ExternalProject.cmake:1702 (message):
Line 'CMAKE_C_COMPILER=gcc' does not match regex.  Ignoring.
Call Stack (most recent call first):
/usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/ExternalProject.cmake:2766 (_ep_command_line_to_initial_cache)
/usr/local/Cellar/cmake/3.12.3/share/cmake/Modules/ExternalProject.cmake:2840 (_ep_extract_configure_command)
```
The drawback of this approach is that cmake shows different compiler that make for external project.

Add cmake option to set external MOD2C

---

tests/unit/endian/swap_endian_noasm.cpp

Small fix to solve errors when compiling tests with PGI.

Fixed SWAP_ENDIAN_DISABLE_ASM error when using PGI

---

coreneuron/nrniv/nrnoptarg.cpp

- No default configuration file needed with the exact name "config"
- Fixes #93

Removed warning for absence of default config file with name "config"

---

coreneuron/nrniv/nrn_setup.cpp
coreneuron/nrniv/nrnoptarg.cpp
coreneuron/nrnoc/eion.cpp
coreneuron/utils/progressbar/progressbar.c
coreneuron/utils/progressbar/progressbar.h

- Added an interval between progress bar prints
- Max number of progress bar prints set to 1000
- Keeps ETA updated regularly
- Fixes #116

Fixing large stdout issue

---

extra/nrnivmodl-core
extra/nrnivmodl_core_makefile.in

The install script string was not outputting quotes correctly.
We also changed `echo` to `printf` since it's a more portable command.
Fixes installation with spack.

nrnivmodl-core script fix

---

coreneuron/nrniv/nrn_setup.cpp
coreneuron/nrnoc/register_mech.cpp

Fixes issue with simulation not running if a mod file is different between Neuron and CoreNeuron even if it is not used in the simulation.

Run simulation with different mod files if they are not used

---

coreneuron/CMakeLists.txt
coreneuron/utils/randoms/Random123/features/clangfeatures.h
coreneuron/utils/randoms/Random123/features/gccfeatures.h

Newer clang versions will throw warnings at lines like this:
```c
#define FOO (defined(BAR))
```
Expand those defines into proper macros

Fix defines in random123 to suppress Wexpansion-to-defined warnings

---

tests/jenkins/install.sh

Load modules for GPU build based on the typical script for
building CoreNeuron with GPU support found here:
https://github.com/BlueBrain/CoreNeuron/issues/145#issuecomment-478051198

Fix Jenkins pipeline

---

tests/jenkins/install.sh

- Removed loading boost module
- updated CMAKE_C_FLAGS and CMAKE_CXX_FLAGS with the latest cuda
version which is used
- Disable ABI due to CXX11_ABI incompatibilities between PGI and
underneath GCC 6.4.0 adding "-D_GLIBCXX_USE_CXX11_ABI=0
-DR123_USE_SSE=0" flags to DCMAKE_CXX_FLAGS:STRING

Fix for Jenkins pipeline after PGI update to 19.4

---

coreneuron/nrniv/nrn_setup.cpp

This change corresponds to changes in NEURON repository
fb82d1998

pc.nrncore_run direct should not delete arrays owned by NEURON.

---

extra/nrnivmodl_core_makefile.in

**Problem**
When creating libnrnmech in mac the subsequent link would bring part of
the original output dir into the link entry. That is because mac writes
all outpyt libname in the install_name (similar to soname). Further, to
be foundable via rpath, `@rpath` had to be in the name.
This patch fixes both issues and special-core now works in MAC

Fixing soname/install_name mac linking probs

---

tests/jenkins/nrnivmodl.sh

Instead of using a specific version of neuron, query the available modules to find a parallel neuron module

Changed pinned parallel version of neuron to generic parallel version

---

coreneuron/nrniv/main1.cpp
coreneuron/nrniv/profiler_interface.h
coreneuron/nrnmpi/mpispike.cpp
coreneuron/nrnoc/fadvance_core.cpp
coreneuron/nrnoc/treeset_core.cpp
coreneuron/utils/ispc/globals.cpp

As there is existing implementation of `instrumentor` struct, I have created a `namespace` named `instrumentor` other than `detail` and kept `phase` struct inside it. Please let me know if you think the design should be different.
Fix https://github.com/BlueBrain/CoreNeuron/issues/158.

Added instrumentor::phase struct API implementation

---

coreneuron/nrniv/nrn_setup.cpp

- Avoids segmentation fault when accessing it in write_phase2 of nrn_checkpoint.cpp

Moved deletion of nrnthread_chkpnt to nrn_cleanup 

---

coreneuron/nrniv/output_spikes.cpp

The bug is reproduced when calling std::min/max_element() when spikevec_time is empty.
The use of those functions with an empty range returns the end iterator. Attempting to dereference this iterator is undefined behavior (segmentation fault in most cases).

Fix bug when spikes vector is empty

---

coreneuron/nrniv/main1.cpp
coreneuron/nrniv/output_spikes.cpp
coreneuron/nrniv/output_spikes.h
coreneuron/utils/string_utils.cpp
coreneuron/utils/string_utils.h

- Clear spike vectors after forward skip
- Change slow strcat function with more efficient memcpy

Slow out.dat generation fixes

---

CMakeLists.txt
extra/nrnivmodl_core_makefile.in

- when cmake is run, PYTHONPATH is setup correctly and nmodl
with sympy can be used.
- for nrnivmodl-core workflow, PYTHONPATH needs to be set
in the makefile so that nrnivmodl is self contained.

Set PYTHONPATH for nrnivmodl-core workflow

---

coreneuron/utils/reports/nrnreport.cpp

- Calculate minimum number of steps to record/buffer due to mindelay
- Report tstop is now the minimum between the duration of the simulation and the report EndTime

Set number of reporting steps to record and stop reports before tstop if necessary

---

coreneuron/CMakeLists.txt

- Fixed the add_custom_command call
- Added scopmath as a dependency to coreneuron as it is needed for the
custom command to succeed (it links with scopmath down the line).

Make scopmath a depdendency for coreneuron

---

coreneuron/mech/modfile/hh.mod
coreneuron/nrniv/nrn_filehandler.cpp
coreneuron/nrniv/nrn_filehandler.h
coreneuron/nrniv/nrn_setup.h
coreneuron/nrniv/partrans.h
coreneuron/nrniv/partrans_setup.cpp

Fixes issue where `CoreNeuron` crashed when it didn't find a `<gid>_gap.dat` because this `gid` didn't have any gap junctions.
Thanks @pramodk for the help!
- Fixes #206

Gap junction fix

---

coreneuron/nrniv/profiler_interface.h

Profiling tools such as LIKWID require the name of the phases at beginning and end of the profiling to match, in order to allow e.g. for nested phases.
So we are now storing the phase name at construction, to re-use it during destruction.

use phase name to close the profiling phase

---

coreneuron/CMakeLists.txt
extra/CMakeLists.txt
extra/nrnivmodl-core.in
extra/nrnivmodl_core_makefile.in
tests/jenkins/nrnivmodl-core.sh

Install script was transformed into a config file being saved/loaded

nrnivmodl-core: adding -n name and dropping install script

---

coreneuron/nrniv/nrn_checkpoint.cpp

NetCon with no target is allowed  in checkpoint
set to pnttype = 0 and pntindex = -1

fix for checkpoint saving issue in neurodamus-py:

---

tests/jenkins/Jenkinsfile

I tried adding a new variable named `CORENEURON_BRANCH` and export it to the user to launch the CI based on that branch. Adding another branch to the `Git SCM` module of based on the `CORENEURON_BRANCH` variable while it seemed to work in the beginning, at some point broke and PRs were not launched with the correct branch.
Reverted the `sha1` variable and used only this to get the `Jenkinsfile` in jenkins configuration.

Fix Jenkins plan manual launch variable

---

coreneuron/apps/main1.cpp
coreneuron/mechanism/mech/enginemech.cpp
tests/jenkins/_env_setup.sh
tests/jenkins/install_neuron.sh
tests/jenkins/mod/CaDynamics_E2.mod
tests/jenkins/neuron_direct.py
tests/jenkins/nrnivmodl.sh
tests/jenkins/run_neuron_direct.sh
tests/jenkins/spack_setup.sh

- modl_reg was not called when corenrn_embedded_run was used
for running simulations with in-memory mode transfer
- move corenrn_embedded_run() into enginemech.cpp to avoid
link error for calling coreneuron::modl_reg
fixes #274

Bugfix : Support for using CoreNEURON in embedded mode with external mechanisms

---

CMakeLists.txt
coreneuron/CMakeLists.txt
extra/CMakeLists.txt
extra/nrnivmodl_core_makefile.in

- set PYTHONPATH for nmodl sympy solver passes
- make sure nmodl python module is built before compiling mod files
- install nmodl headers to install prefix
- enable inline pass always (--inline)
- nrnivmodl-core inherit PYTHONPATH correctly
Fixes #278 and #279

Fix issues while NMODL is built with sympy and analytical passes

---

coreneuron/mpi/nrnmpi.cpp

- Replace `omp_get_num_threads()` with `omp_get_max_threads()` to get the
max number of threads that OpenMP can use
- From my understanding `omp_get_num_threads()` run in a "serial" region and always printed `1`
- Related to #292

Fix printing of max threads used by OpenMP

---

extra/nrnivmodl_core_makefile.in

- libscopmath.a was linked to libcorenrnmech with shared library
but was missing in case of static library
- ar doesnt provide way to link two static libraries together.
Hence extrat objects and then combined those together.
fixes #303 #306

Bugfix : add missing link to libscopmath

---

CMake/packages/Findnmodl.cmake
tests/jenkins/install_coreneuron.sh

- Fixes issue finding nmodl when provided with `CORENRN_NMODL_DIR` because of `nmodl_PYTHONPATH`

Update nmodl to latest master

---

coreneuron/CMakeLists.txt

* update mod2c to latest master with fixes for olfactory 3d-bulb model
* minor fix to remove hardcoded python binary name

Use PYTHON_EXECUTABLE instead of python and update mod2c to latest master

---

.travis.yml
coreneuron/CMakeLists.txt

- Fixed NMODL PYTHONPATH in another place in CMake
- Added "sympy --analytic" flag in CoreNEURON build in CI to test if the proper PYTHONPATH of NMODL is set on CoreNEURON

NMODL PYTHONPATH fixes

---

coreneuron/apps/main1.cpp
coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/gpu/nrn_acc_manager.hpp
coreneuron/io/nrn_setup.hpp
coreneuron/network/partrans_setup.cpp
coreneuron/utils/randoms/nrnran123.h

- init_gpu should be called very early before mechanism registration
to make sure all memory is allocated on specific gpu in case of multi-gpu
system (e.g. bbcore_read & acc copyin)
- nrnran123_normal should be marked as acc routine seq
- minor debug message improvement

Bug fixes for gpu execution

---

coreneuron/io/nrn_setup.cpp

This is minor fix to allow rank0 to print message and then abort. Otherwise we get error stack like:
```
Model uses gap junctions
MPT ERROR: Rank 1(g:1) is aborting with error code 1.
Process ID: 308765, Host: r2i3n6, Program: /gpfs/bbp.cscs.ch/project/proj16/kumbhar/pramod_scratch/modeldb-bulb3d-sim/sim/x86_64/special-core
MPT Version: HPE MPT 2.21  08/29/19 00:34:00
MPT: --------stack traceback-------
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
```
With this PR:
```
Model uses gap junctions
Error: ThreshDetect is a different MOD file than used by NEURON!
Error : NEURON and CoreNEURON must use same mod files for compatibility, 1 different mod file(s) found. Re-compile special and special-core!
MPT ERROR: Rank 0(g:0) is aborting with error code 1.
Process ID: …
```

Abort from rank printing error message

---

coreneuron/io/nrn2core_direct.h
coreneuron/io/nrn_setup.cpp
coreneuron/io/output_spikes.cpp

In link with: https://github.com/neuronsimulator/nrn/pull/692 
Should we add an extra parameter to the NEURON callback in order to indicate if writing `output.dat` should be skipped? Or is something we'd like to have at a global level, say a CLI option?

Return all spikes vectors to NEURON

---

.travis.yml
coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/apps/main1.cpp
coreneuron/io/mk_mech.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/network/netpar.cpp
coreneuron/sim/fadvance_core.cpp
coreneuron/utils/nrn_stats.cpp

Sample output when launched from NEURON: 
```
Starting CoreNEURON data generation
Starting CoreNEURON simulation
Additional mechanisms from files
Ca.mod CaDynamics_DC0.mod CaDynamics_E2.mod Ca_HVA.mod Ca_HVA2.mod Ca_LVAst.mod CoreConfig.mod Ih.mod Im.mod K_Pst.mod K_Tst.mod KdShu2007.mod NaTa_t.mod NaTg.mod NaTs2_t.mod Nap_Et2.mod ProbAMPANMDA_EMS.mod ProbGABAAB_EMS.mod ProfileHelper.mod SK_E2.mod SKv3_1.mod TTXDynamicsSwitch.mod VecStim.mod cacumm.mod cacummb.mod cagk.mod cal2.mod can2.mod cat.mod gap.mod h.mod halfgap.mod kadist.mod kaprox.mod kca.mod kd.mod kd2.mod kdb.mod kdrbca1.mod kdrca1.mod km.mod kmb.mod na3n.mod naxn.mod netstim_inhpoisson.mod new_calcium_channels.mod
WARNING: nrn_nrn_wrote_conc support on GPU need to validate!
psolve …
```

Add --verbose option Closes #338

---

coreneuron/apps/main1.cpp
coreneuron/mechanism/mech/modfile/pattern.mod
coreneuron/mechanism/patternstim.cpp
coreneuron/nrniv/nrniv_decl.h
tests/jenkins/Jenkinsfile
tests/jenkins/run_corenrn.sh

This allows specifying separate patternstim file for restore part:
- start event chain by sending event at t+0
- discard events from file that arrive before t
Here is internal ticket: https://bbpteam.epfl.ch/project/issues/browse/CNEUR-313
```
Current implementation of coreneuron expects whole spike-replay file provided on command line. We have fixed this by https://github.com/BlueBrain/CoreNeuron/pull/121.
But this might result in loss of spikes in case of:
* user specify tstop = 100 for part0
* simulator stop at 100.1
* pattern.dat in part1 has event at 100.05
One way to avoid this error is to always provide whole pattern.dat file to coreneuron. Is that feasible solution? (note that the implementation in coreneuron needs to be updated to avoid storing whole file)
```
@nrnhines : do we …

Patternstim fix : allow restore phases to provide new pattern-stim

---

coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/gpu/nrn_acc_manager.hpp
coreneuron/sim/fadvance_core.cpp

- NEURON can request various trajectories from CoreNEURON
- In this implementation we are just updating voltage vector
and satisfy the use case of olfactory 3d-bulb model
- We will need more fine grain approach (for future PR)

Update voltage vector from GPU to CPU if trajectories are recorded

---

coreneuron/permute/cellorder.cpp

Fixes #369.
There are several other issues in this context that  I would like to discuss.

Unitialized pointer. Later segmentation fault after freeing.

---

coreneuron/mpi/nrnmpi.cpp
coreneuron/utils/memory_utils.cpp

Remove:
* Remove spi/include/kernel/memory.h from BG-Q time
* HPM from BG-Q days
* unused nrnmpi_checkbufleak

Remove unused code

---

coreneuron/network/netcvode.cpp
coreneuron/network/tqueue.cpp
coreneuron/network/tqueue.hpp
coreneuron/network/tqueue.ipp
coreneuron/utils/nrn_stats.cpp

- histotically queue stats related code was added
to get an idea of number of events in the particular
simulation
- we haven't used this for years and I haven't found
this anything useful anyway.

Remove queue statistics related (dead) code

---

coreneuron/io/nrn_setup.cpp
coreneuron/io/phase2.cpp
coreneuron/permute/cellorder.cpp
coreneuron/permute/cellorder.hpp

I separated these into small independent commits. Especially solicit your opinion on not implementing assignment and copy constructors. Also, if those are useful to have, is it a good idea to specifically have ```delete``` correspond to ```new`` and ```free``` corespond to ```malloc```.

Minor fixes

---

coreneuron/io/output_spikes.cpp

Fixes Ivan's last problem mentioned in #369.

Clear spike vectors after writing or transferring.

---

coreneuron/CMakeLists.txt
coreneuron/apps/main1.cpp
coreneuron/io/core2nrn_data_return.cpp
coreneuron/io/core2nrn_data_return.hpp
coreneuron/io/nrn2core_direct.h
coreneuron/mechanism/mech/enginemech.cpp

Framework in place.
Interacts with neuronsimulator/nrn#717

Copies to NEURON the voltage, i_membrane_, and mechanism data.

---

coreneuron/io/nrn2core_direct.h
coreneuron/io/nrn_setup.cpp
coreneuron/io/phase1.cpp
coreneuron/io/phase1.hpp
coreneuron/network/netpar.cpp
coreneuron/nrniv/nrniv_decl.h

Only for direct transfer mode is it allowed that a negative srcgid is not
in the same thread as the NetCon target.
To enable thread determination an std::vector<int> involving the name
netcon_negsrcgid_tid is associated with netcon_srcgid in that when a negative
gid appears in netcon_srcgid, the tid is the value of the element in
netcon_negsrcgid_tid.
This pr is assciated with neuronsimulator/nrn#735

If a netcon_srcgid is negative, need to determine the thread.

---

coreneuron/utils/vrecitem.h

- changing base class method prototype result into bug for
virtual method in PlayRecordEvent
@alkino : culprit was [this commit](https://github.com/BlueBrain/CoreNeuron/pull/385/files#diff-c79cec806ef8ef3de58d9ed516974213) :

Bug fix for PR #385 : add missing `const` for virtual method

---

coreneuron/io/nrn_setup.cpp
coreneuron/io/phase2.cpp
coreneuron/mechanism/mechanism.hpp

Until now NetSendBuffer_t was allocated at a fixed size that could not
be changed. When using buffered net_send and invoking multiple
net_send's in INITIAL blocks in NMODL it may happen that we run out of
buffer. Currently this case is not handled and causes a buffer overflow.
As a first step NetSendBuffer_t has been given a constructor and
destructor as well as a grow function that doubles all internal buffer
sizes and copies data to the new buffers.

Allow NetSendBuffer_t to grow

---

extra/nrnivmodl-core.in
extra/nrnivmodl_core_makefile.in

For example, this enables the call:
`nrnivmodl-core -a "sympy --analytic" mod/`
Partially addresses issue #344

Add support for inserting nmodl flags in nrnivmodl-core calls

---

extra/nrnivmodl_core_makefile.in

Nmodl default flag message was always printing the ispc one
regardless of @CORENRN_ENABLE_ISPC@ status

Fix nmodl default flags message (issue #400)

---

coreneuron/apps/main1.cpp
coreneuron/mpi/nrnmpi.cpp
coreneuron/mpi/nrnmpidec.h
coreneuron/mpi/nrnmpiuse.h

We have to decide what to do with other arguments just like `-p4` that is not valid with the new parser.
Does someone know what is `nrn_music`?

No more check parameters from argc / argv but from the parser. Fix #184

---

coreneuron/CMakeLists.txt
coreneuron/permute/cellorder.cpp

- remove outdated sm arch flags (for CUDA 11.0)
- brek from parallel region not allowed with latest
PGI version
fixes #412
fixes #411

Fixes for latest PGI compiler 20.9 via NVIDIA-HPC-SDK

---

extra/nrnivmodl_core_makefile.in

If mod2c fail, the file is generated but empty, because of that they are
not generated again and it fails later in a complicated way

Use of DELETE_ON_ERROR for generating mod files

---

extra/nrnivmodl_core_makefile.in

related error:
```
/home/runner/work/nrn/nrn/build/bin
=> Binary creating x86_64/special-core
/tmp/cc9fs5kJ.o: In function `main':
/home/runner/work/nrn/nrn/build/share/coreneuron/coreneuron.cpp:34: undefined reference to `solve_core'
collect2: error: ld returned 1 exit status
make[3]: *** [x86_64/special-core] Error 1
/home/runner/work/nrn/nrn/build/share/coreneuron/nrnivmodl_core_makefile:161: recipe for target 'x86_64/special-core' failed
make[2]: *** [external/coreneuron/coreneuron/CMakeFiles/nrniv-core] Error 2
external/coreneuron/coreneuron/CMakeFiles/nrniv-core.dir/build.make:74: recipe for target 'external/coreneuron/coreneuron/CMakeFiles/nrniv-core' failed
CMakeFiles/Makefile2:1276: recipe for target 'external/coreneuron/coreneuron/CMakeFiles/nrniv-core.dir/all' failed
make[1]: …
```

Fix undefined reference to `solve_core' race condition

---

extra/nrnivmodl-core.in

The column consumes an argument (wrong). I just did not know
exactly how it was working. Sorry.
Thx Pramod and Fernando for spotting this
Fix BBPBGLIB-629 in confluence

fixup! nrnivmodl core verbose consumes an arg

---

CMake/AddCLI11Submodule.cmake
CMake/AddNmodlSubmodule.cmake

- nmodl initialize necessary submodules. so we do not need to
do recursive initialize that adds extra submodules for no reason
- update nmodl to latest master
Todo:

Update nmodl submodule to latest master and avoid recursive cloning

---

coreneuron/io/nrn_setup.cpp
coreneuron/io/phase2.cpp

**Phase2 setup of pnttype2presyn causes race.**
Move the setup to main thread prior to phase2.
Fixes neuronsimulator/nrn#884
See test-mpithread.py at neuronsimulator/nrn#884 and follow build instructions. Without this change the error reliability is high with:
```
mpiexec -n 4 nrniv -mpi -python test-mpithread.py
```

Setup pnttype2presyn in main thread to avoid race.

---

coreneuron/CMakeLists.txt
extra/nrnivmodl_core_makefile.in

- CoreNEURON supports caliper instrumentation with -DCORENRN_ENABLE_CALIPER_PROFILING=ON
- If caliper profiling is enabled then nrnivmodl-core should add path to lib directory of caliper
- Change order of mpi and caliper libraries due to issue LLNL/Caliper/issues/176
Related to #449
```bash
cmake .. -DCORENRN_ENABLE_CALIPER_PROFILING=TRUE -Dcaliper_DIR=/gpfs/.../gcc-8.3.0/caliper-2.0.1/share/cmake/caliper
make -j
```
and run test as:
```
$ CALI_CONFIG_PROFILE=mpi-runtime-report srun -n 3 bin/x86_64/special-core -e 10 -d ../tests/integration/ring --mpi
== CALIPER: (0): default: Registered aggregation service
== CALIPER: (0): default: Registered event trigger service
== CALIPER: (0): default: Registered timestamp service
== CALIPER: (0): default: Registered MPI service …
```

Fix caliper link lines for nrnivmodl-core

---

CMake/OpenAccHelper.cmake
README.md
coreneuron/CMakeLists.txt
coreneuron/gpu/nrn_acc_manager.cpp
extra/CMakeLists.txt

- Fix pthread link error (#428)
- Error if GPU support is enabled without PGI compiler
Currently GPU support is only enabled via OpenACC and
tested only with PGI compiler only.
- Change CUDA to 9.0 as we are no longer testing/developing
with old CUDA. And PGI compilers are also shipping newer
CUDA libraries.
fixes #428

Minor improvements and clarifications for GPU build

---

coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/io/mech_report.cpp
coreneuron/io/mech_report.h
coreneuron/io/nrn_setup.cpp
tests/integration/CMakeLists.txt

Access feature through `--count_mechs` runtime option.
Cherry picked 055368d from @pramodk and added a runtime option to enable/disable this step.
Fixes #444
```bash
cmake ..
make -j8
nrnivmodl mod
./bin/nrnivmodl-core mod
./x86_64/special script.py
./x86_64/special-core --count_mechs --tstop=10 --datpath=coredat
```

Printing mechanism count and mech stats to log

---

.github/workflows/coreneuron-ci.yml
CMake/AddRandom123Submodule.cmake

`Random123` submodule needs to be in a proped `CoreNEURON` subdirectory, so we try to avoid finding from system paths.
- OS: macos github runner

Avoid using system paths for Random123

---

CMake/MakefileBuildOptions.cmake
CMake/OpenAccHelper.cmake
CMakeLists.txt
coreneuron/CMakeLists.txt
coreneuron/apps/main1.cpp
coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/mechanism/eion.cpp
coreneuron/mechanism/mechanism.hpp
coreneuron/mechanism/membfunc.hpp
coreneuron/mechanism/register_mech.cpp
extra/CMakeLists.txt
extra/nrnivmodl-core.in
extra/nrnivmodl_core_makefile.in
tests/jenkins/Jenkinsfile
tests/jenkins/_env_setup.sh
tests/jenkins/install_coreneuron.sh
tests/jenkins/spack_setup.sh

In order to simplify makefile generation with multiple targets (#442)
this PR refactor some of the CMake flags handling:
* move all makefile related options into single file MakefileBuildOptions.cmake
* remove all option processing from extra/CMakeLists.txt
* minor simplifications in makefile; removing ISPC_INTEROP definition
Usual CMake build options; no changes in CMake
CI_BRANCHES:NEURON_BRANCH=master,SPACK_BRANCH=bbpv-2021-01

CMake build options refactoring for Makefile

---

CMake/MakefileBuildOptions.cmake
tests/jenkins/install_coreneuron.sh

Fixess issue with `CORENRN_NMODL_FLAGS` not being written in the `nrnivmodl_core_makefile`
```bash
cmake .. -DCORENRN_ENABLE_NMODL=ON -DCORENRN_NMODL_FLAGS="sympy --analytic codegen --force"
make -j8
./bin/nrnivmodl-core mod
```
- OS: macOS
- Compiler: GCC
- Backend: CPU

Fix passing CORENRN_NMODL_FLAGS to nrnivmodl_makefile

---

coreneuron/io/reports/report_handler.cpp

Fixed issue when passing synapse id to the reporting library 

Fix issue with synapse reports

---

coreneuron/io/core2nrn_data_return.cpp
coreneuron/io/mem_layout_util.hpp
coreneuron/io/nrn_checkpoint.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/setup_fornetcon.cpp
coreneuron/mechanism/patternstim.cpp
coreneuron/nrniv/nrniv_decl.h
coreneuron/permute/node_permute.cpp
coreneuron/utils/memory.h

An enum exists to know that 0 mean SoA and 1 AoS, use it.
I have to move it, so that enum is available everywhere.

Use enum Layout everywhere

---

.github/workflows/coreneuron-ci.yml
README.md

Use gcov/lcov to generate coverage reports on running `make test` and report coverage in codecov.io

Add codecov coverage tests

---

CMakeLists.txt
tests/jenkins/run_neuron.sh

When both `CORENRN_ENABLE_NMODL` and `CORENRN_ENABLE_GPU` are true then these arguments were added twice, which triggers a compilation error:
```
file: File does not exist: acc
```
This PR removes the duplication. It arises because in this case [we take](https://github.com/BlueBrain/CoreNeuron/blob/88e02a533764de29aadfcddec2eb0b64ca1ff884/extra/nrnivmodl_core_makefile.in#L73)
```
nmodl_arguments_c=@NMODL_ACC_BACKEND_ARGS@ @NMODL_COMMON_ARGS@
```
where [`NMODL_ACC_BACKEND_ARGS` contains `acc --oacc`](https://github.com/BlueBrain/CoreNeuron/blob/88e02a533764de29aadfcddec2eb0b64ca1ff884/CMake/MakefileBuildOptions.cmake#L29) and [`NMODL_COMMON_ARGS` includes `CORENRN_NMODL_FLAGS`](https://github.com/BlueBrain/CoreNeuron/blob/88e02a533764de29aadfcddec2eb0b64ca1ff884/CMake/Makefi …

Avoid duplicating `acc --oacc` arguments to NMODL

---

tests/jenkins/run_neuron.sh
tests/jenkins/run_neuron_direct.sh

Fixes neuron direct test run in Jenkins pipeline CI.
The test was failing with the following output:
```
mpirun -n 1 nrniv -python /jenkins/07/workspace/oss.coreneuron.pipeline/tests/jenkins/neuron_direct.py -mpi
numprocs=1
NEURON -- VERSION + master (d28fcb8+) 2021-01-30
Duke, Yale, and the BlueBrain Project -- Copyright 1984-2019
See http://neuron.yale.edu/neuron/credits
Traceback (most recent call last):
File "/jenkins/07/workspace/oss.coreneuron.pipeline/tests/jenkins/neuron_direct.py", line 14, in <module>
h.soma.insert("CaDynamics_E2")
ValueError: argument not a density mechanism name.
>>> 
+ cd -
/jenkins/07/workspace/oss.coreneuron.pipeline
+ rm -rf /jenkins/07/workspace/oss.coreneuron.pipeline/build_Wonv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
Traceback …
```

Fixes neuron_direct test in the Jenkins CI

---

CMakeLists.txt
tests/jenkins/run_neuron.sh
tests/jenkins/run_neuron_direct.sh

* Fixes neuron_direct test in the Jenkins CI (#487)
* Avoid duplicating `acc --oacc` arguments to NMODL (#486)

Cherry-pick bug fixes from master for release/1.0

---

CMake/GitRevision.cmake

Without this change then the presence of:
```
[log]
showSignature = True
```
in the local `~/.gitconfig` file breaks compilation of CoreNEURON because the signature information is not escaped properly for inclusion in the generated C++ string literal.
(see also: https://github.com/neuronsimulator/nrn/pull/955)

[Trivial] Fix compilation if git signatures shown by default

---

coreneuron/io/global_vars.cpp
coreneuron/io/lfp.hpp
coreneuron/mechanism/register_mech.cpp
coreneuron/nrnconf.h
tests/unit/alignment/alignment.cpp
tests/unit/lfp/lfp.cpp
tests/unit/queueing/test_queueing.cpp

In the `lfp` PR during the calculation of `lfp` there is a variable `PI` used. The value of this variable should be same as `NEURON` and the variable used by the mod files.

Pass PI value from NEURON to CoreNEURON

---

CMakeLists.txt
tests/unit/alignment/CMakeLists.txt
tests/unit/cmdline_interface/CMakeLists.txt
tests/unit/interleave_info/CMakeLists.txt
tests/unit/queueing/CMakeLists.txt

- CoreNEURON's CTest tests may now run as part of the top-level `make test` target when CoreNEURON is built as a submodule of NEURON.
- Removed some trivial usage of `file(GLOB ...)` to collect lists of source files. [The CMake documentation advises against this pattern](https://cmake.org/cmake/help/v3.19/command/file.html#glob).
Build NEURON with `-DNRN_ENABLE_CORENEURON=ON` and `-DNRN_ENABLE_TESTS=ON`, changing `nrn/external/coreneuron` to point at this branch. Run `make test` in the NEURON build directory.

Enable CoreNEURON tests when running as a submodule of NEURON

---

coreneuron/CMakeLists.txt

This changes how dependencies are declared in CMake to ensure that `nrnivmodl` is not called to recompile `halfgap.mod` ever time the project is built.
I tested with CoreNEURON built as a submodule of NEURON. After running
```bash
cmake ..
make -j
make -j # this should barely do anything, but without it this PR it was rerunning nrnivmodl.
```

Prevent nrnivmodl running on every build

---

extra/nrnivmodl_core_makefile.in
tests/jenkins/run_neuron_direct.sh

- coreneuron mechanism lib is `<arch>/.libs`/libcorenrnmech*
- fix symlink : it must be relative path to the parent directory 
* We were deleting `<arch>/.libs` directory. This potentially break the workflow if user execute nrnivmodl first and then nrnivmodl-core.
* symlink should be relative from `x86_64/.libs` directory 
Should fix https://github.com/neuronsimulator/nrn/issues/1007

Do not remove <arch>/.libs but only coreneuron mechanism libray

---

coreneuron/apps/main1.cpp
coreneuron/mechanism/eion.cpp
coreneuron/mechanism/membfunc.hpp

- nrn_ghk was recently added but `acc routine seq` was missing
- nrn_ghk uses celsius which is an extern variable. All extern
variables require `acc declare create/copyin` caluse.
- As global variables can be initialized after device attachment
(celsius in this case), we need to make sure celsius is updated
on the device.
- Replacing `data` clause with `update device` is sufficient. In
this case `data` clause doesn't update value on device when
checked in eion.cpp.
```bash
cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/install -DCORENRN_ENABLE_GPU=ON
make -j8
make install
cd nrn/test/pynrn/
nrnivmodl-core .
```
- BB5
- Compiler: nvhpc/20.9 and CUDA 11
- Backend: [e.g. GPU] …

Fix GPU compilation issue when nrn_ghk is used in the MOD files

---

tests/unit/lfp/CMakeLists.txt

```      
Start  5: lfp_test
Could not find executable /home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/lfp_test_bin
Looked in the following places:
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/lfp_test_bin
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/lfp_test_bin
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/Release/lfp_test_bin
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/Release/lfp_test_bin
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/Debug/lfp_test_bin
/home/magkanar/bbp_repos/nrn/build_test/external/coreneuron/tests/unit/lfp/Debug/lfp_test_bin …
```

Fix lfp test when running from NEURON

---

coreneuron/gpu/nrn_acc_manager.cpp

- acc_memcpy_to_device is used to copy the device pointer
- so we have to use an address of the device pointer and size of 
pointer ie. `sizeof(IvocVect*)`
- note that IvocVect is already copied by previous acc_copyin call
- this issue was introduced in #283
fixes #501
See #501 for how to test this

Bug fix for copying VecPlay's IvocVect object on GPU

---

coreneuron/gpu/nrn_acc_manager.cpp

- patternstim is a special mechanism whose data is not copied on
gpu
- when we update whole GPU data back to CPU, we should skip the
patternstim
fixes #503

Bug fix for GPU : Patternstim shouldn't be copied from GPU to CPU

---

.gitlab-ci.yml

This allows the CoreNEURON CI to be used in regression tests of the `hpc/gitlab-pipelines` helper repository that powers the GitLab pipeline.
Make a change to the `hpc/gitlab-pipelines` repository and see that CoreNEURON is tested with your changes.

Enable use of this pipeline in an external test.

---

coreneuron/sim/fast_imem.cpp

Initialize `fast_imem` struct with 0 in the beginning to make sure that there are no garbage in the first iteration.
There is no easy way to do this but comparing reports of `i_membrane` in `Neurodamus`.
- OS: Linux
- Compiler: Intel
- Backend: CPU

Fix fast_imem initialization to 0

---

coreneuron/apps/main1.cpp
coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/gpu/nrn_acc_manager.hpp
coreneuron/mechanism/mech/mod2c_core_thread.hpp
coreneuron/sim/scopmath/newton_struct.h
coreneuron/sim/scopmath/newton_thread.cpp
coreneuron/sim/scopmath/sparse_thread.cpp

This PR ensures that calls to `acc_copyin(...)` have corresponding calls to `acc_delete(...)`, fixing errors such as
```
FATAL ERROR: variable in data clause is partially present on the device: name=(unknown)
```
when repeatedly running CoreNEURON on GPU in the same process.
Also fix handling of artificial cells to avoid problems with `IntervalFire`.
#513 remains valid, because #197 means that minor additional changes are required in NEURON.
Follow instructions in https://github.com/BlueBrain/CoreNeuron/issues/513.
- OS: BB5
- Compiler: PGI 21.2
- Backend: GPU

Add OpenACC data cleanup.

---

.gitlab-ci.yml

- Revert GPU build to RelWithDebInfo.
- Re-enable phase 2 GPU nodes.
- Add reference to issue #518
- Re-add +gpu variant.

Fixup GPU CI configuration.

---

.cmake-format.changes.yaml
coreneuron/CMakeLists.txt
coreneuron/gpu/nrn_acc_manager.cpp
extra/nrnivmodl_core_makefile.in

This uses a CMake helper function (`cpp_cc_build_time_copy`) introduced in https://github.com/BlueBrain/hpc-coding-conventions/pull/95 and refined in https://github.com/BlueBrain/hpc-coding-conventions/pull/96 to define build rules that copy files from the source tree to the build tree. This means that more dependencies can be tracked automatically and that CMake does not have to be re-run so often. Also make some implicit dependencies explicit.
Also remove a warning (`Warning: VectorPlay used but NOT implemented on GPU!`) that is outdated.

CMake / build system improvements + remove outdated warning

---

coreneuron/io/nrn2core_direct.h
coreneuron/io/phase2.cpp

**Fixes neuronsimulator/nrn#1154**
Changes related to neuronsimulator/nrn#1155
Without this fix, the problem is exhibited with a modified tests/testcorenrn/testvecplay.hoc
```
hines@hines-T7500:~/neuron/vecplay-transfer/external/tests/testcorenrn$ git diffdiff --git a/testvecplay.hoc b/testvecplay.hoc
index ac1cc82..a9e34aa 100644
--- a/testvecplay.hoc
+++ b/testvecplay.hoc
@@ -45,6 +45,8 @@ for (gid = pc.id; gid < ncell; gid += pc.nhost) {
cells.append(cell)
}
+pc.nthread(2)
+
pc.spike_record(-1, tvec, idvec)
cvode.cache_efficient(1)
```
With
```
ctest -R testcorenrn_vecplay
```
NEURON is configured with:
```
$ cmake .. -DCMAKE_INSTALL_PREFIX=install -DIV_DIR=$HOME/neuron/ivcmake/build/install -DPYTHON_EXECUTABLE=`which python3` -DNRN_ENABLE_TESTS=ON -DNRN_ENABLE_CORENEURON=ON …
```

Fix VecPlayContinuous direct mode error with multiple threads.

---

.gitlab-ci.yml

Enable support for `CI_BRANCHES` specifications in PR descriptions for the GitLab CI. The implementation lives in [hpc/gitlab-pipelines!17](https://bbpgitlab.epfl.ch/hpc/gitlab-pipelines/-/merge_requests/17).
Closes #505.
**Use certain branches for the CI**

Enable branch specification in GitLab CI.

---

coreneuron/CMakeLists.txt
extra/CMakeLists.txt

While trying to build `NEURON` with `CoreNEURON` and `NMODL` I came across an issue where the tests of `NEURON` were trying to compile mod files using `nrnivmodl_core_makefile` that used `nmodl`, before the compilation of `nmodl` binary.
This pull request does the following:
- Adds dependency of `nmodl` if needed when configuring `nrnivmodl-core`
- Addsdependency of `nrnivmodl-core` in `coreneuron` target to make sure all the components of `coreneuron` are built before other external targets depend on it
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce if there is no integration test added with this PR. Please also list any relevant details for your test configuration
```bash
git clone …
```

Added dependency for nrnivmodl-core and nmodl

---

coreneuron/io/output_spikes.cpp
coreneuron/io/reports/report_configuration_parser.cpp

The [scheduled NEURON CI](https://github.com/neuronsimulator/nrn-build-ci) [failed](https://github.com/neuronsimulator/nrn-build-ci/runs/2453857595?check_suite_focus=true) this morning. This was because the `fedora:latest` Docker image is now Fedora 34, which uses gcc 11.0.1.
The new compiler / standard library seems to be more pedantic about includes; this PR adds some missing `#include <limits>` where `std::numeric_limits<...>` is used.
The tests actually fail locally with an illegal instruction error, but I suspect this might be a problem with Docker etc. so let's try this in the CI anyway.
```bash
docker run -it --rm fedora:latest
dnf install -y bison cmake diffutils dnf flex gcc gcc-c++ git \
openmpi-devel libXcomposite-devel libXext-devel make …
```

Add missing includes, fix gcc11 compilation.

---

coreneuron/io/nrn_setup.cpp
coreneuron/mechanism/membfunc.hpp
coreneuron/mechanism/register_mech.cpp

* This feature was not entirely supported and only placeholders were there
* Add the correct signature of destructor's callbacks (mod_f_t)

Handle correctly destructor block

---

CMake/OpenAccHelper.cmake

The CoreNEURON CMake has some special handling for PGI/NVHPC compilers. In older CMake versions these were all labelled as "PGI", but in CMake v3.20+ then the NVHPC compilers have their own identifier.
Build with CMake v3.20+, an NVHPC compiler and GPU support. The build will fail without this change.
- OS: BB5
- Compiler: NVHPC 21.2
- Backend: GPU

CMake v3.20+ no longer labels NVHPC as PGI.

---

coreneuron/gpu/nrn_acc_manager.cpp

Remove the call to `acc_shutdown(acc_device_nvidia)` (OpenACC API) when cleaning up GPU data. This invoked undefined behaviour in case CoreNEURON was executed on GPU multiple times in the same process. See also: https://github.com/BlueBrain/CoreNeuron/pull/515.
The `coreneuron_modtests::datareturn_py` test, which runs three multiple CoreNEURON simulations from one Python script, is sensitive to this issue. This was not actually failing on `master`, but it probably could have been. Some other draft modifications that  used the `acc_map_data` and `acc_unmap_data` calls exposed the issue.
- OS: BB5
- Compiler: NVHPC 21.2
- Backend: GPU

Remove call to acc_shutdown when cleaning up GPU data.

---

tests/jenkins/install_coreneuron.sh

spack location --latest was not finding the latest installed libsonata-report version.
In order to fix this issue now we force to find versions > 1.0

Jenkins CI: Find latest libsonata-report version

---

.gitlab-ci.yml

This should make the CI more reliable until an issue with some nodes is resolved.
Look at the GitLab CI and check that the NVHPC/GPU build jobs are not failing when downloading the sources for dependencies.

Restrict which GPU nodes the GitLab CI builds run on.

---

CMakeLists.txt

If Coreneuron is itself inside an external directory it will be excluded.
Fix #547

Fix for make clang-format when project is submodules

---

.github/workflows/clang_cmake_format_check.yaml
.github/workflows/coreneuron-ci.yml
.github/workflows/coverage.yml

* drop previous runs for subsequent updates (master, release & PRs)
* make use of new GHA concurrency feature
* concurrency group consists of workflow_name#github_ref
* see https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

GHA CIs: drop previous runs

---

CMake/OpenAccHelper.cmake
CMakeLists.txt
README.md
coreneuron/CMakeLists.txt

This means we can force consistency between the CUDA and OpenACC code and avoid linker errors.
Previously, compilation was successful on machines with a sufficiently modern GPU, [as the NVHPC compiler modifies its behaviour based on the current system hardware](https://docs.nvidia.com/hpc-sdk/archive/21.2/compilers/hpc-compilers-user-guide/index.html#compute-cap), but it failed on machines with no GPU. This was because the default list of compute capabilities (3.5, 5.0, 6.0 and 7.0 in NVHPC 21.2) included a value (3.5) that was not compatible with the options used to compile the CoreNEURON CUDA library.
Also explicitly specify the CUDA version to avoid a similar issue with a newer CUDA version being assumed for the OpenACC compilation than was used for the CUDA part on a …

Explicitly specify NVIDIA compute capabilities.

---

.gitlab-ci.yml

With https://github.com/BlueBrain/spack/pull/1172 the dependencies of the GPU CI are now deployed. This means we can remove some workarounds that avoided building these dependencies in the CI.
Also, running GPU builds on non-GPU nodes is now supported so we can remove some constraints there.

Simplify GitLab CI config

---

CMake/OpenAccHelper.cmake

This was needed for old PGI versions (circa 16.x), but it does not seem to be important any more.
The documentation also suggests that the syntax of this option has changed and the old formulation is no longer valid.
(`-Minline` also seems to have strange semantics when it is passed alongside `-MD` and `-MT` -- as is done by modern CMake versions for dependency tracking -- leading to a huge amount of debug information being printed, so removing this is desirable.)
Build NEURON+CoreNEURON with MOD2C+GPU backends and ran the CTest suite. Also checked that the `.mod` files from https://github.com/pramodk/nrntraub and https://github.com/pramodk/dentate compile with `nrnivmodl-core` (with the exception of `ri.mod`).
- OS: BB5
- Compiler: …

Remove -Minline flag.

---

coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/gpu/nrn_acc_manager.hpp
coreneuron/mechanism/patternstim.cpp
coreneuron/mpi/nrnmpi.cpp
coreneuron/sim/fadvance_core.cpp
coreneuron/sim/fast_imem.cpp
coreneuron/sim/treeset_core.cpp

This PR adds support for copying the `fast_imem` data structures to/from a compute device/GPU and adds OpenACC `#pragma`s to offload computations on those data. This closes https://github.com/BlueBrain/CoreNeuron/issues/197.
This will allow us to improve the coverage of the NEURON tests, where some checks [are disabled](https://github.com/neuronsimulator/nrn/blob/d9462cc81b5d3a264b947a825499cbea1e22eee1/test/coreneuron/test_direct.py#L47-L49) because of this issue. It is also necessary to get the test suite running with CoreNEURON+NMODL+GPU, because NMODL's generated code crashes if the data structures are not copied to the GPU.
Some fixes were also needed to the `.mod` file translation to make the NEURON tests pass, so this changes the submodule commits to include …

Implement fast_imem calculation on GPU.

---

.gitlab-ci.yml

This will enable the export of log files from the GitLab CI so they are accessible directly from GitHub.

Export GitLab CI logs.

---

coreneuron/io/reports/sonata_report_handler.cpp

Passes the report units to the libsonatareport library
CI_BRANCHES:NEURODAMUS_CORE_BRANCH=sandbox/jblanco/report_units,SPACK_BRANCH=report_units,

Support SONATA report units

---

.github/workflows/coverage.yml

After codecov.io's security issue, it's worth adding extra checks for the bash uploader.

shasum checks for codecov.io bash uploader

---

coreneuron/gpu/nrn_acc_manager.cpp

* Analysis of the bug:
- Blue Brain model (channel-benchmark) was showing diferent spikes
after few timesteps. Spikes were shifted and initially appeared
to be floating point discrepencies.
- Closely looking into NET_RECEIVE method revealed that the mechanism
data accessed in net_receieve function was wrong. Somehow accessing
variables like NMDA_ratio was showing wrong values. The nrn_state()
had correct values.
- The net_receieve function was accessing ml->data inside OpenACC loop.
Accessing ml->data was providing different pointer inside OpenACC loop.
* Fix for the bug:
- some mechanisms can have dparam semantics for diam data and it is
added into nt->data (after matrix elements).
- When calculating offert for mechanism data, this extra semantics
data was not considered. Adjusting the …

Bug fix for the GPU execution of BBP model: issue with mechanism data offset

---

coreneuron/gpu/nrn_acc_manager.cpp

Fixes #586 
This issue is a bit hard to reproduce however I managed to reproduce it consistently with the tests added for the `psolve-direct` branch in `NEURON` and `CoreNEURON`, where `psolve` is running multiple times from the same script using `CoreNEURON`.
```bash
git clone git@github.com:neuronsimulator/nrn.git -b psolve-direct
cd nrn
git submodule update --init --recursive
cd external/coreneuron
git checkout fix_openacc
cd ../..
cmake .. -DCMAKE_INSTALL_PREFIX=./install -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=OFF -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON -DCORENRN_ENABLE_GPU=ON
make -j16
make install
ctest -V -R coreneuron_modtest
```
- OS: RedHat
- Compiler: NVHPC 21.2/CUDA 11.0.2
- Version: `psolve-direct`/`master` …

Fixed issue with "variable in data clause is partially present on the device: name=(unknown)"

---

CMakeLists.txt

Setting CMAKE_CXX_STANDARD only add the flag, but maybe that the compiler is
too old and does not fully support it.
This way, it will fail before compiling and avoid understandable errors during
compilation.
Fix #228

Check that c++14 is fully supported before compiling

---

coreneuron/mechanism/eion.cpp
coreneuron/nrnconf.h

As described in #498, all extern variables require acc declare
create/copyin caluse. As variables can be updated after device
attachment (like celsius), #498 has taken care to update them.
fixes BlueBrain/nmodl/issues/707
Todos:
Run testderiv.hoc test from testcorenrn repository
- OS: BB5
- Compiler: default nvhpc + CUDA
- Backend: GPU
CI_BRANCHES:NEURON_BRANCH=pramodk/derivimplicit-legacy-fix,

Fix compilation error with derivimplicit solver and use of celsius as extern variable

---

CMake/OpenAccHelper.cmake
CMakeLists.txt
README.md
coreneuron/CMakeLists.txt
coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/utils/memory.h
coreneuron/utils/profile/profiler_interface.h
coreneuron/utils/randoms/nrnran123.cu
tests/jenkins/install_coreneuron.sh
tests/unit/alignment/CMakeLists.txt
tests/unit/cmdline_interface/CMakeLists.txt
tests/unit/interleave_info/CMakeLists.txt
tests/unit/lfp/CMakeLists.txt
tests/unit/queueing/CMakeLists.txt

This changeset changes the CMake configuration of GPU builds to:
These changes force compilation to proceed slightly differently to a standard mixed CUDA/C++ project. Instead of allowing CMake to generate an explicit device linker step, i.e.
```
nvcc -dc -o foo.cu.o foo.cu ...
nvcc -dlink -o dlink.o *.cu.o ...
ar qc libcudastuff.a *.cu.o dlink.o
```
before compiling OpenACC/GPU-enabled C++ code (which emits additional device code):
```
nvc++ -acc -gpu=cuda11.0,cc70 -o main main.cpp -lcudastuff ...
```
we instead let `nvc++` do the device code linking itself, i.e. something more like
```
nvc++ -acc -gpu=cuda11.0,cc70 -o main.cpp.o -c main.cpp
nvc++ -acc -gpu=cuda11.0,cc70 -cuda -o main main.cpp.o *.cu.o # -cuda but no dlink.o!
```
which seems to give correct results. This …

Modernise CMake/CUDA and fix link issues

---

CMake/OpenAccHelper.cmake
CMakeLists.txt
coreneuron/CMakeLists.txt
coreneuron/apps/main1.cpp
coreneuron/utils/memory.cpp
coreneuron/utils/memory.h
coreneuron/utils/profile/cuda_profile.cu
coreneuron/utils/randoms/nrnran123.cu
coreneuron/utils/randoms/nrnran123.h

This fixes CPU execution of GPU builds on machines that do not have GPUs, which were previously segfaulting due to the use of the `__managed__` keyword. Now the handling of Random123 state is more explicit for host/device. This was only added in https://github.com/BlueBrain/CoreNeuron/pull/595, but the issue wasn't noticed at the time because the GPU-enabled CI only executes tests on machines with GPUs.
Also add a pair of helper functions `coreneuron::[de]allocate_unified()` that wrap `cudaMallocManaged()` in GPU builds if `--gpu` was passed at runtime and fall back to `new`/`delete` otherwise, and a method `coreneuron::unified_memory_enabled()` that queries whether this condition is met.
Additionally add a C++ allocator template `coreneuron::unified_allocator<T>` that …

Do not use __managed__ in GPU builds. Add utils.

---

CMakeLists.txt
README.md

Following an internal discussion, we've decided to bump minimum CMake version to 3.15 for maintainability purposes.
Driven by #609.
CI_BRANCHES:NEURON_BRANCH=cmake315,

Bump minimum supported CMake version to 3.15

---

CMake/config/CompilerFlagsHelpers.cmake
CMakeLists.txt
coreneuron/CMakeLists.txt
coreneuron/sim/fadvance_core.cpp
coreneuron/utils/progressbar/progressbar.cpp
coreneuron/utils/progressbar/progressbar.hpp
extra/nrnivmodl_core_makefile.in

Drop C language code (1 file!) from CoreNEURON.
Also use this as an excuse to test https://github.com/BlueBrain/nmodl/pull/723.
Build CoreNEURON and note that it doesn't search for a C compiler (at all, if you build with NMODL).
- OS: BB5
- Compiler: NVHPC 21.7
CI_BRANCHES:NMODL_BRANCH=olupton/ccache,

Make CoreNEURON C++ only.

---

coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/sim/fadvance_core.cpp

This updates the handling of variable trajectories in GPU builds. Previously, each value of interest was individually uploaded to the host every time step. Now the values are accumulated in GPU memory and uploaded at the end of the simulation, eliminating one `acc wait` and many `acc update self` clauses each time step.
Closes https://github.com/BlueBrain/CoreNeuron/issues/611.
Run the standard CTest test suite in a GPU build.
- OS: BB5
- Compiler: NVHPC 21.7
- Version: olupton/gpu-trajectories branch
- Backend: GPU

Record variable trajectories on GPU

---

CMake/MakefileBuildOptions.cmake
CMake/OpenAccHelper.cmake

* Need to explitly use -Mautoinline to make sure functions
like `net_receieve_kernel` are inlined by NVHPC compiler.
* Note that `-Mautoinline` is not added to `CMAKE_CXX_FLAGS`
because it's not default with NVHPC compiler. We are
adding this flag only for `.mod` related `.cpp` files.
* See also #573
fixes #518
Run the standard CTest test suite in a GPU build.
- OS: BB5
- Compiler: NVHPC 21.7
- Version: olupton/gpu-trajectories branch
- Backend: GPU

Fix GPU/OpenACC build issues with CMake build_type=Debug

---

coreneuron/io/core2nrn_data_return.cpp
coreneuron/io/nrn2core_data_init.cpp

`assert(pnt->_i_instance == pntindex);` was not working properly for permute type different than 0.
Apply fix by @nrnhines mentioned in https://github.com/BlueBrain/CoreNeuron/issues/619#issuecomment-906377376 
Please include a summary of the change and which issue is fixed or which feature is added.
Follow instructions in https://github.com/BlueBrain/CoreNeuron/issues/619#issue-979334600
- OS: RedHat
- Compiler: Intel
- Version: master branch
- Backend: CPU
CI_BRANCHES:NEURON_BRANCH=hines/psolve-permute-test,

Fix assertion in nrn2core_transfer_watch_condition

---

coreneuron/CMakeLists.txt
coreneuron/io/mech_report.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/output_spikes.cpp
coreneuron/mpi/nrnmpi.cpp
coreneuron/mpi/nrnmpi.h

- All MPI related code is now under coreneuron/mpi
- Separate cmake target for mpi related code and
include MPI headers for only these files
- Remove unnecessary headers (and MPI include)
- Spike output function is factored into a separate file
Preparation for #600
No new options/instructions.

Refactor/re-organising MPI related code

---

coreneuron/sim/fast_imem.cpp
coreneuron/sim/fast_imem.hpp
coreneuron/sim/finitialize.cpp

The equation for initialization of i_membrane_ is slightly different than its per time step calculation after each integration step.
This follows NeuronSimulator/nrn#1237
As it is currently inconvenient to print certain kinds of information during an offline run,  this was tested using a patch which prints the values of node index and i_membrane for every node after nrn_finitialize is called. I.e:
```
hines@hines-T7500:~/neuron/fastimem/external/coreneuron/coreneuron$ git diff
diff --git a/coreneuron/apps/main1.cpp b/coreneuron/apps/main1.cpp
index cbca538..4adabcb 100644
--- a/coreneuron/apps/main1.cpp
+++ b/coreneuron/apps/main1.cpp
@@ -470,6 +470,24 @@ extern "C" void mk_mech_init(int argc, char** argv) {
mk_mech((corenrn_param.datpath).c_str());
}
+static void print_fast_imem(const …
```

CoreNEURON offline (file) mode initializes fast i_membrane.

---

coreneuron/io/global_vars.cpp

All USERDOUBLE are supposed to be transferred to CoreNEURON in online mode (In offline mode they all are supposed to appear in the globals.dat file). Although unlikely, it is possible for the last item in the NEURON symbol table to be a USERDOUBLE.  In that case that variable will not appear in the CoreNEURON list of globals. This error has been fixed for offline (file transfer) mode with NeuronSimulator/nrn#1437.  This PR fixes the issue for online (direct transfer) mode.
This bug revealed itself as a minor memory leak  in nrn/test/pynrn with:
```
valgrind --leak-check=full --show-leak-kinds=definite `pyenv which python` -m pytest .
```
It turned out that ```cao0_ca_ion``` ended up as the last symbol in the NEURON symbol table due to the test statement
``` …
```

If last symbol in NEURON is USERDOUBLE, was not processed as GLOBAL.

---

CMakeLists.txt
coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/apps/main1.cpp
coreneuron/permute/cellorder.cpp
coreneuron/permute/cellorder.cu
coreneuron/permute/cellorder.hpp
coreneuron/utils/utils_cuda.h
tests/integration/CMakeLists.txt

Implementation of solve_interleaved2 using CUDA + Improvement of OpenACC counterpart (issue #603)
The solve_interleaved1 should not be used since the algorithm is not optimized for GPUs. On the other hand, solve_interleaved2 is constructed with GPU-architecture in mind, i.e. the computations (forward/backward substitution on Hines matrices) are done in batches of warpsize(=32). This guarantees coalesced memory access and minimal branch divergence.
Regarding the openACC version of solve_interleaved2, I have forced the vector_length to be warpsize(=32) given the structure of the implementation. _This change resulted in 15-20% increase in performance._
Regarding the CUDA version of solve_interleaved2, I have tried many alternatives using shared/constant memory but because the …

Implementation of solve_interleaved2 using CUDA + Improvement of OpenACC counterpart (issue #603)

---

.gitlab-ci.yml

After https://github.com/BlueBrain/spack/pull/1285 `coreneuron+nmodl` no longer depends on `eigen` in BlueBrain's Spack.
The CoreNEURON CI plan previously specified that the `eigen` dependency be built with GCC, which now causes an error because that dependency no longer exists.
Without this change, new CI runs (which take `develop` of `BlueBrain/spack`) will fail.

[CI] CoreNEURON no longer depends on Eigen.

---

.gitlab-ci.yml

https://github.com/BlueBrain/CoreNeuron/pull/631 disabled `ccache` in the GitLab CI because of an issue, which I could not reproduce later (https://github.com/BlueBrain/nmodl/issues/731).
This PR re-enables `ccache`, which should make the CI faster.

Re-enable ccache in GitLab CI

---

coreneuron/utils/ivocvect.cpp
coreneuron/utils/ivocvect.hpp

fixes #638 
```
/gpfs/bbp.cscs.ch/ssd/slurmTmpFS/kumbhar/2608407/spack-stage/spack-stage-neurodamus-hippocampus-1.5-3.3.2-4mxtb7v3n52yea62g3bp4axur5d66daz/spack-src/build_hippocampus
=> Binary creating x86_64/special-core
/gpfs/bbp.cscs.ch/home/kumbhar/workarena/systems/bbpv/softwares/sources/spack/opt/spack/linux-rhel7-x86_64/nvhpc-21.2/coreneuron-1.1a-jblyvn/share/coreneuron/coreneuron.cpp:
nvlink error   : Undefined reference to '_ZN57_INTERNAL_35_x86_64_corenrn_mod2c_GluSynapse_cpp_52e3392310coreneuron19_net_receive_kernelEdPNS0_13Point_processEid' in 'x86_64/libcorenrnmech_hippocampus.a:GluSynapse.o'
pgacclnk: child process exit status 2: /gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/deploy/externals/2021-01-06/linux-rhel7-x86_64/gcc-9.3.0/nvhpc-21.2-67d2qp/Linux_x86_64/21.2/compilers/bin/to …
```

make vector_capacity and vector_vec as routine seq

---

CMake/OpenAccHelper.cmake

Drop one C++11-specific line in CoreNEURON.
Hijack this change to test channel benchmark CI.
CI_BRANCHES:NEURON_BRANCH=olupton/channel-benchmark

Update NMODL to include C++14 changes.

---

coreneuron/utils/memory.cpp

Only call `::operator delete(void*, std::size_t)` if it is defined,
otherwise fall back to `::operator delete(void*)`. Despite the
two-argument version being in the C++14 standard, Clang only enables it
if `-fsized-deallocation` is passed. [[link]](https://clang.llvm.org/cxx_status.html#n3778).
This fixes compilation of this file with Clang 12.
Language Feature | C++14 Proposal | Available in Clang?
-- | -- | --
C++ Sized Deallocation | N3778 | Clang 3.4 (7)
(7): In Clang 3.7 and later, sized deallocation is only enabled
if the user passes the <code>-fsized-deallocation</code> flag. The user must
supply definitions of the sized deallocation functions, either by providing them
explicitly or by using a C++ standard library that does. <code>libstdc++</code>
added these …

Respect __cpp_sized_deallocation macro.

---

coreneuron/apps/main1.cpp
coreneuron/io/output_spikes.cpp
coreneuron/io/output_spikes.hpp
coreneuron/io/reports/nrnreport.hpp
coreneuron/io/reports/report_configuration_parser.cpp

Adapt to the new feature from libsonata-report for spike report writing, i.e. do create_file/write data/close_file in separate steps.  
The spike data also requires gid offset for each population, use default 0 at the moment.
The Simulation Stack CI
CI_BRANCHES:SPACK_BRANCH=spike_multipop,NEURODAMUS_CORE_BRANCH=sandbox/weji/report_multipop,PYNEURODAMUS_BRANCH=sandbox/weji/report_multipop,

Adapt to the new api in libsonata-report for sonata spike report

---

.gitlab-ci.yml

Allow GPU CI jobs to run on nodes not in the `prod` partition. Tests the resolution of HELP-14481.

Allow GPU test jobs to run on all GPU nodes.

---

coreneuron/apps/corenrn_parameters.cpp

Fix range of permute option to [0, 2]

---

.github/workflows/coreneuron-ci.yml
.github/workflows/coverage.yml
CMakeLists.txt
coreneuron/apps/corenrn_parameters.cpp
coreneuron/io/global_vars.cpp
coreneuron/io/nrn2core_data_init.cpp
coreneuron/io/nrn_checkpoint.hpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/phase2.cpp
coreneuron/io/phase2.hpp
coreneuron/mechanism/register_mech.cpp
coreneuron/network/multisend_setup.cpp
coreneuron/network/partrans_setup.cpp
coreneuron/permute/cellorder.hpp
coreneuron/permute/cellorder1.cpp
coreneuron/permute/cellorder2.cpp
coreneuron/permute/node_permute.cpp
coreneuron/sim/scopmath/sparse_thread.cpp
coreneuron/utils/nrntimeout.cpp

hines: I think CORENRN_DEBUG_QUEUE can be deleted. Those are easy to add back if needed. I think INTERLEAVE_DEBUG should be kept as it consists of a very elaborate test which would be tedious to add back. I'd be happy to make it work again. I expect CHKPNTDEBUG to also be useful again in the future. DEBUG is too generic to be much use but to the extent that they are just printf, I think they can be removed and if more than a dozen lines in one place, assessed in context.

Let all DEBUG being compiled

---

README.md

- Did not raised an issue, but I was copy pasting the cmake configurations and noticed this minor typo: missing a `\`
- Hope It helps even if just a little

fix: cmake options missing one '\'

---

.gitlab-ci.yml
tests/jenkins/install_coreneuron.sh

After the Slurm upgrade we can no longer specify multiple partitions.

Fix BB5-based CI

---

coreneuron/io/core2nrn_data_return.cpp

Related to neuronsimulator/nrn#1534
This is part of the fix for issue neuronsimulator/nrn#1531
Build the NEURON version for neuronsimulator/nrn#1534
```bash
cmake .. -G Ninja -DCMAKE_INSTALL_PREFIX=install -DPYTHON_EXECUTABLE=`pyenv which python` -DNRN_ENABLE_RX3D=OFF -DCMAKE_BUILD_TYPE=Debug -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON
ninja install
ninja test
cd ../test/coreneuron
nrnivmodl -coreneuron mod
python test_datareturn.py
```
CI_BRANCHES:NEURON_BRANCH=hines/nrn2core-tq-bug,

All interthread events on queue before transfer.

---

coreneuron/network/multisend_setup.cpp

Turn off printing of multisend setup space/time info
See neuronsimulator/nrn#1537
CI_BRANCHES:NEURON_BRANCH=hines/multisend-fix,

Turn off printing of multisend setup space/time info

---

CMakeLists.txt
coreneuron/CMakeLists.txt

Adds an option `CORENRN_EXTERNAL_BENCHMARK_DATA` that we can point to a shared directory on Permutter/Ascent/BB5. A draft directory on BB5 is `/gpfs/bbp.cscs.ch/project/proj16/olupton/nersc-gpu-hackathon-dec-2021`, which exists (possibly out of date) at `$CFS/ntrain9/neuron/nersc-gpu-hackathon-dec-2021` on Perlmutter and `/ccsopen/proj/gen170/neuron/nersc-gpu-hackathon-dec-2021` on Ascent.
If this is available, building CoreNEURON will also create a `special-core` binary that can execute the `channel-benchmark` input data provided in `CORENRN_EXTERNAL_BENCHMARK_DATA`.

[Hackathon] Add a temporary option for benchmark data.

---

coreneuron/CMakeLists.txt

* create build/benchmark folder before trying to use it
* run nrnivmodl-core in parallel than serially (too slow)
Fixes issues described on Perlmutter hackathon wiki page: https://github.com/BlueBrain/CoreNeuron/wiki/NERSC-GPU-hackathon-(Dec-2021)/45e645f183289f17050a89bd5e2397732e630ed1#notes-from-pramods-review
Perlmutter

Minor changes for building on perlmutter

---

coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp

Set by default the number of warps to execute in a large reasonable number and update the related documentation
Cell permute 2 algorithm is distributing the cells in groups based on the `nwarp` option based to the CLI. Since it used to be 0 as default all the cells were executed using one warp on GPU with the `--cell-permute 2` option and there was no interleaving of the cells in the way they are sorted in memory.
This generated suboptimal performance.
A quick solution provided is setting the `nwarp` to a reasonable large number that might not generate the best load balancing but should be enough to hide large latencies introduced by memory accesses.
TODO:
- Find a better and dynamic way to set it

Set by default the number of warps

---

coreneuron/CMakeLists.txt
coreneuron/utils/randoms/nrnran123.cu

This speeds up initialisation when running on GPU if Boost is available.
Previously many small Random123 stream objects were allocated separately using (ultimately) `cudaMallocManaged` in GPU builds. This is very slow, and makes setup on GPU much slower than on CPU.
This change places a pool allocator "in front of" `cudaMallocManaged`, which both makes allocation faster and (hopefully) reduces the number of unified memory page faults during simulation.
In a small `channel-benchmark`-based test this makes model setup 3x faster.

Add memory pool for Random123 streams.

---

coreneuron/utils/randoms/nrnran123.cu

Fix a silly bug in the branch of https://github.com/BlueBrain/CoreNeuron/pull/702 taken when Boost is not found.

Fix Boost-free compilation.

---

coreneuron/gpu/nrn_acc_manager.cpp

small openacc fixes

---

coreneuron/gpu/nrn_acc_manager.cpp

This way is more convenient for us.
CI_BRANCHES:NMODL_BRANCH=hackathon_main,NEURON_BRANCH=master,

OMP: use pragmas instead of c-api to allocate and delete target data

---

coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/utils/offload.hpp

omp_get_mapped_ptr is only for omp >= 5.1
gcc and clang still does not implement it
CI_BRANCHES:NMODL_BRANCH=hackathon_main,NEURON_BRANCH=master,

Implement omp_get_mapped_ptr until it is available

---

coreneuron/apps/corenrn_parameters.hpp
coreneuron/permute/cellorder.cu

Set nwarp to very big number for optimal parallelization and improve a bit grid config of CUDA solve_interleaved2

GPU implementation improvements

---

coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/apps/main1.cpp
tests/unit/cmdline_interface/test_cmdline_interface.cpp

Adds a `reset()` method to the `corenrn_parameters` struct, which resets members to their default values.
This should help with https://github.com/BlueBrain/CoreNeuron/pull/701/files#r758813278.
It is challenging to support `corenrn_param = corenrn_parameters{}` as a way of doing the same thing because of the CLI11 struct embedded inside.

Add corenrn_parameters::reset() method.

---

.gitlab-ci.yml

The NEURON test suite is quite large now, and https://github.com/neuronsimulator/nrn/pull/1556 is going to add a larger single test that requests 16 ranks, so it seems reasonable to increase the number of allocated cores. The old default was 8.

Request 16 cores for NEURON test jobs

---

coreneuron/gpu/nrn_acc_manager.cpp

Mechanism are not use on GPU if they are artificial, so stop sending it.
For clarity, clean handling of ml inside nrn_acc_manager by dividing into functions
CI_BRANCHES:NMODL_BRANCH=hackathon_main,NEURON_BRANCH=master,

Separate handling of ml inside nrn_acc_manager

---

CMake/OpenAccHelper.cmake

Pass the `-cuda` option to the NVIDIA HPC compilers when OpenACC/OpenMP are enabled.
See https://forums.developer.nvidia.com/t/enabling-openmp-offload-breaks-openacc-code/196643, and this also seems to help with Random123.
TODO:
CI_BRANCHES:NEURON_BRANCH=master,NMODL_BRANCH=hackathon_main,

Compile with -cuda

---

CMake/config/CompilerFlagsHelpers.cmake
tests/jenkins/Jenkinsfile
tests/jenkins/nrnivmodl-core.sh
tests/jenkins/nrnivmodl.sh

- Clang compiler flags were not added
- Because of this, no flags were set for RelWithDebInfo or
any other build types
- Update tqperf test script for Jenkins CI
- update tqperf GitHub URL
- mod files are now into two directories, need to use mod + modx 
```bash
module load unstable gcc llvm cmake python 
cmake ..
-- Configured CoreNEURON 1.0
--
-- You can now build CoreNEURON using:
--   cmake --build . --parallel 8 [--target TARGET]
-- You might want to adjust the number of parallel build jobs for your system.
-- Some non-default targets you might want to build:
-- --------------------+--------------------------------------------------------
--  Target             |   Description
-- --------------------+----------------------------------------------- …
```

Set compilation flags for different build types with Clang

---

.gitlab-ci.yml

Streamline the pipeline a little by using a single build of NMODL with GCC instead of building it with both Intel and NVHPC. 
Also allocate more resources for build jobs to avoid too many of them landing on the same nodes and killing the filesystem.
Extend an existing fix for NVHPC to avoid building `py-{cython,numpy}` with Intel, which seems fragile.
~Start the CUDA MPS daemon before running GPU tests. Unfortunately this does not work well if we do not allocate the GPU node exclusively, as only a single instance can run per node, so we also allocate the node exclusively..which is a bit resource-heavy.~
Hopefully make the job names easier to parse.
Bump the mod2c submodule to include https://github.com/BlueBrain/mod2c/pull/76 to improve `ccache` performance in GitLab CI. …

GitLab CI improvements

---

CMakeLists.txt

Remove a CMake version check as it appears that 3.21 and 3.22 do not behave as documented.
This fixes Spack GPU builds with more modern CMake versions. Spack sets `CUDAHOSTCXX` to point to the C++ compiler (`nvc++` in GPU builds) and, despite the documentation, this is not overridden by `CMAKE_CUDA_HOST_COMPILER` being set to point to `g++`. The version of `nvc++` in the new deployment (21.11 using GCC 11.2 headers) is not supported as a host compiler for `nvcc` in CUDA (11.5.1) -- [link](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements).
```bash
spack install coreneuron%nvhpc+gpu
```
with a CMake version such as 3.21 will return an error like
```
Compiling the CUDA compiler identification source file …
```

Extend CMake/CUDAHOSTCXX/... workaround.

---

.github/workflows/test-as-submodule.yml
extra/nrnivmodl_core_makefile.in

Add a CI plan that tests building CoreNEURON as a submodule of NEURON.
https://github.com/neuronsimulator/nrn/pull/1576 shows that a recent PR to CoreNEURON broke this compilation mode, and we didn't spot it at the time.
TODO:
Fixes #743

CI for CoreNEURON as submodule + fix

---

.github/workflows/test-as-submodule.yml
coreneuron/CMakeLists.txt

* Add CI for dynamic MPI under NEURON
- Currently there is no CI that builds neuron+coreneuron with dynamic MPI support
- This should help to detect errors like below early
https://dev.azure.com/neuronsimulator/nrn/_build/results?buildId=4649&view=logs
* Add missing include path for dynamic MPI targets
* Cherry-pick improvement from #744 
Azure CI failure in https://github.com/neuronsimulator/nrn/pull/1580
```bash
cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/install -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=OFF -DPYTHON_EXECUTABLE=`which python3` -DCORENRN_ENABLE_GPU=OFF   -DCORENRN_ENABLE_NMODL=OFF  -DCMAKE_INSTALL_PREFIX=../install -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON -DNRN_ENABLE_MPI_DYNAMIC=ON
make -j12
```
**Use certain branches for the …

Enable dynamic MPI in github CI when built as neuron submodule

---

.gitlab-ci.yml

Added `Unified Memory` build with `mod2c` in Gitlab CI similar to the old Jenkins pipeline
Partly tackles #732 
**Use certain branches for the CI**

Add Unified Memory build in Gitlab CI

---

coreneuron/permute/cellorder.cu

New commit is just after https://github.com/BlueBrain/hpc-coding-conventions/pull/111, which should allow CoreNEURON to be formatted with `clang-format-13`. 
Also include a formatting fix to a CUDA file that is apparently not formatted in the CI.

Bump hpc-coding-conventions commit.

---

.gitlab-ci.yml

Tune which compilers are used for different bits of the dependency graph.
Along with https://github.com/BlueBrain/spack/pull/1422 this should mean that each job only builds the software it is supposed to, without recompiling any extra dependencies.

Migrate to 2022 deployment for GitLab CI.

---

.github/workflows/coreneuron-ci.yml
CMake/OpenAccHelper.cmake

Fore CoreNEURON release 1.0.1. Goes with https://github.com/neuronsimulator/nrn/pull/1603
CI_BRANCHES:NEURON_BRANCH=8.0.1-cherries,

CoreNEURON 1.0.1 Release

---

.gitlab-ci.yml

Simplify GitLab CI configuration following upstream changes to `hpc/gitlab-helpers` and https://github.com/BlueBrain/spack/pull/1468.
- it is now more convenient to trigger CoreNEURON's pipeline manually, with `NEURON_BRANCH` and `NMODL_BRANCH` optionally set
- we no longer rely on (the default) `CI_BRANCHES:NEURON_BRANCH=master` to make the SimulationStack child pipeline build `neuron@develop` instead of `neuron`
This PR is also serving as a way of testing the NEURON C++ changes in https://github.com/neuronsimulator/nrn/pull/1597 in the CoreNEURON CI, but that is not relevant to the actual changeset in CoreNEURON.
CI_BRANCHES:NEURON_BRANCH=olupton/more-c++,SPACK_BRANCH=olupton/test-neuron-c++

GitLab CI improvements (also testing NEURON C++)

---

.gitlab-ci.yml

This is a backwards-compatible change that should keep things working smoothly when we merge a planned change to the `gitlab-pipelines` helper. It simply makes it explicit that the commit on which the CoreNEURON pipeline is running is also the commit of CoreNEURON that should be built by Spack. This is already the (implicit) default.

CORENEURON_COMMIT: ${CI_COMMIT_SHA}

---

.gitlab-ci.yml

This line:
```yaml
SPACK_ENV_FILE_URL: $SPACK_SETUP_COMMIT_MAPPING_URL
```
means that all `*_COMMIT` variables, plus `SPACK_BRANCH` and `SPACK_DEPLOYMENT_SUFFIX`, will be transferred to the child `blueconfigs` pipeline.
CI_BRANCHES:LIBSONATA_REPORT_BRANCH=master

Use simplified GitLab CI helpers.

---

coreneuron/gpu/nrn_acc_manager.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/setup_fornetcon.cpp
coreneuron/sim/multicore.hpp

`NrnThread` had two `std::vector<size_t>` members, `_fornetcon_perm_indices` and `_fornetcon_weight_perm`, that were ignored when copying data to the GPU in `nrn_acc_manager.cpp`. This meant that trying to access these arrays from the GPU led to a crash.
Is it awkward to handle non-trivial data structures such as `std::vector` in our current implementation, so for simplicity I have simply replaced this with `new[]` and `delete[]`. Hopefully we can improve this soon in a safer way.
Closes https://github.com/BlueBrain/CoreNeuron/issues/512.
TODO:
Use the `olupton/fornetcon-gpu` branch of NEURON and run the `coreneuron_modtests::fornetcon_py_gpu` test with `ctest -R coreneuron_modtests::fornetcon_py_gpu`.
- OS: BB5
- Compiler: NVHPC 22.2 …

fornetcon: fix GPU execution.

---

coreneuron/mechanism/eion.cpp

Different sections might have different `iontype`s as for example in the M1 NetPyNE simulation. Instead of reading only the `iontype` of the first section of each mechanism, calculate each one based on its `iontype`.
I was able to reproduce this issue only with the M1 simulation and when setting `cfg.singleCellPops = 1`.
This option `Creates pops with 1 single cell (to debug)` according to the documentation.
Using this branch I managed to get the same spikes between CoreNEURON and NEURON on CPU with `debug` builds enabled and using direct mode.
With this PR M1 and S1 simulations (reduced versions with `cfg.singleCellPops = 1`) generate the same spikes in CPU with debug and release builds on offline and online CoreNEURON execution.
Related neuron part …

Fix pdata calculation

---

.github/pull_request_template.md
.github/workflows/test-as-submodule.yml

Previously the closing ``` ` ``` was in the wrong place, meaning that `nrn_branch` was not set correctly and CoreNEURON PRs were always tested against `master` of NEURON.
Note that in bash:
```console
$ foo=bar | echo hello
hello
$ echo $foo
$
```
Also tweak the first `awk` command so that it would not match `CI_BRANCHES:FOONEURON_BRANCH=bar`.
This should fix a failure in https://github.com/BlueBrain/CoreNeuron/pull/772.
Also update the GitHub PR template to include a comment describing usage of the `CI_BRANCHES` keyword.

Fix test-as-submodule CI.

---

coreneuron/CMakeLists.txt
coreneuron/utils/randoms/nrnran123.cu

A clean branch based on the experiments done during GPU hackathon implementing OpenMP offloading for
coreneuron random123, keeping the CUDA/OpenACC versions intact so they can coexist.
```bash
cmake .. -G Ninja -DCORENRN_ENABLE_GPU=ON -DCORENRN_ENABLE_NMODL=ON \
-DCORENRN_NMODL_FLAGS=""  -DCMAKE_CUDA_COMPILER=nvcc  \
-DCMAKE_CXX_FLAGS="-DR123_USE_SSE=0" -DCMAKE_CXX_COMPILER=nvc++ \
-DCORENRN_ENABLE_OPENMP=ON -DCORENRN_ENABLE_OPENMP_OFFLOAD=ON
ninja
ctest -V
```
- BB5

OpenMP target offloading for random123

---

coreneuron/CMakeLists.txt
extra/nrnivmodl_core_makefile.in
tests/CMakeLists.txt
tests/unit/cmdline_interface/CMakeLists.txt
tests/unit/interleave_info/CMakeLists.txt
tests/unit/lfp/CMakeLists.txt
tests/unit/queueing/CMakeLists.txt

* Before this PR, user always had to do `nrnivmodl -coreneuron .``
to have coreneuron with default mechanisms.
* This was because we were not installing default mechanism library
libcorenrnmech.so into install dir. Note that this was done in order
to force user to re-build optimised library from vendor compiler
like Intel.
* But, for basic demonstration and testing, I think it's always
helpful to ship default mechanism library as a fallback. The
library <arch>/libcorenrnmech.so built by user will be preferred anyway.
* Update nmodl to latest master
If you install neuron+coreneuron as:
```console
cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/install -DNRN_ENABLE_INTERVIEWS=OFF -DNRN_ENABLE_RX3D=OFF  -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON …
```

Default/Minimal coreneuron should be always available in NEURON (cpu)

---

coreneuron/io/phase2.cpp
coreneuron/mechanism/register_mech.cpp

Same extension as neuronsimulator/nrn#1722
Tested on NEURON side with
```bash
cmake ... -DNRN_ENABLE_CORENEURON=ON -DNRN_ENABLE_TESTS=ON
make
ctest -R coreneuron_modtests::test_pointer_py_cpu
```
CI_BRANCHES:NEURON_BRANCH=hines/bamult,

Allow multiple BEFORE/AFTER blocks of same type in a mod file.

---

coreneuron/utils/ivocvect.cpp
coreneuron/utils/ivocvect.hpp

In NEURON the return type is `IvocVect*`:
https://github.com/neuronsimulator/nrn/blob/331e75096ea984d2945ba675b44d969470fbfb1b/src/oc/oc_ansi.h#L191
This helps us to prepare for https://github.com/neuronsimulator/nrn/pull/1597.

vector_new1: make return type match NEURON.

---

coreneuron/io/nrn2core_data_init.cpp
coreneuron/io/nrn_checkpoint.hpp
coreneuron/io/nrn_setup.hpp
coreneuron/io/phase2.cpp
coreneuron/io/phase2.hpp
coreneuron/io/reports/nrnreport.cpp
coreneuron/network/multisend.hpp
coreneuron/network/partrans.cpp
coreneuron/permute/cellorder1.cpp
coreneuron/sim/fadvance_core.cpp
coreneuron/utils/ivocvect.hpp
coreneuron/utils/randoms/nrnran123.cu
coreneuron/utils/utils.cpp
coreneuron/utils/utils.hpp

Fix warnings in non-generated code with `-Wall` and AppleClang 13.1.6.

Fix clang warnings.

---

extra/nrnivmodl-core.in

In case of wheel, neuron wrapper scripts will set `CORENRN_PERLEXE` variable pointing to perl binary
to use. Prefer that over `PERL_EXECUTABLE` found by CMake
Fixes #799

Avoid perl path from build machine appearing in wheel / binary distributions

---

coreneuron/CMakeLists.txt

Without this, builds without MPI have linker errors about `dlsym` and `dlerror`, which are used in `core/nrnmpi.cpp`.

Fix building without MPI.

---

coreneuron/permute/cellorder.hpp
coreneuron/permute/cellorder1.cpp
coreneuron/utils/memory.h
tests/unit/interleave_info/check_constructors.cpp

Fixes an AddressSanitizer error in the test.

Use matched allocation/deallocation routines.

---

CMakeLists.txt

* CMake's `get_target_property` might return `<VAR>-NOTFOUND` and
hence it should be checked before it's usage
* As mentioned in neuronsimulator/nrn/issues/1788, it can result
into error like:
```
=> LINKING executable ./special LDFLAGS are:     -lreadline -lncurses
/users/bp000174/nrn-install/share/nrn/nrnmain.cpp:
/usr/bin/ld: cannot find -lCORENRN_LINK_LIBRARIES-NOTFOUND
```
- Piz-Daint

Check variable return by get_target_property before it's usage

---

.github/workflows/clang_cmake_format_check.yaml
.github/workflows/coreneuron-ci.yml
.github/workflows/coverage.yml
.github/workflows/test-as-submodule.yml

Inspired by https://github.com/BlueBrain/nmodl/pull/879 and seeing if this fixes failures this morning.
Prefer Ubuntu 20.04 to 18.04 and bump major versions of some actions.
Drop sympy version constraints for NMODL and use a debug (not release) build for coverage.

GitHub Actions CI updates

---

CMakeLists.txt

Update the semantic version to match https://github.com/neuronsimulator/nrn/pull/1597, which will be merged imminently.
With https://github.com/neuronsimulator/nrn/pull/1762 and https://github.com/BlueBrain/CoreNeuron/pull/796 CoreNEURON is versioned according to the NEURON scheme. This PR updates CoreNEURON to 9.0.0 so the CoreNEURON submodule commit can be updated in https://github.com/neuronsimulator/nrn/pull/1597.
The CI is running against the branches of https://github.com/neuronsimulator/nrn/pull/1597 and https://github.com/BlueBrain/spack/pull/1624.
CI_BRANCHES:NEURON_BRANCH=olupton/more-c++,NMODL_BRANCH=master,SPACK_BRANCH=olupton/neurodamus

Bump semantic version to 9.0.0

---

README.md
coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/io/mech_report.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/nrn_setup.hpp
coreneuron/mechanism/mechanism.hpp

Report the size of the dynamically allocated memory for each mechanism based on the `ml->data` and `ml->pdata` structures.
Building CoreNEURON and running the following test:
```bash
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=./install -DNRN_ENABLE_CORENEURON=ON -DCORENRN_ENABLE_NMODL=OFF -DCORENRN_ENABLE_GPU=OFF -G Ninja
cmake --build . --parallel 8 --target install
bash tests/integration/ring/integration_test.sh
```
Has the following output:
```
================= MECHANISMS COUNT BY TYPE ===================
Id                 Name      Count   Total memory size (KiB)
0               (null)          0                      0.00
1               (null)          0                      0.00
2           morphology          0 …
```

Print memory footprint of each mechanism

---

.github/workflows/coreneuron-ci.yml
.sanitizers/undefined.supp
coreneuron/mechanism/eion.cpp
coreneuron/sim/solve_core.cpp
tests/CMakeLists.txt
tests/unit/solver/CMakeLists.txt
tests/unit/solver/test_solver.cpp

Add some tests of the various CPU/OpenACC/OpenMP/CUDA implementations of the Hines matrix solver.
These use toy input data that is generated on the fly. Tests cover scenarios such as:
- many small cells
- few large cells
both with hardcoded constant values for the matrix elements and pseudorandom number generation.
The results (`d` and `rhs`) from all available solver implementations are compared to one another in each scenario.
See also #826, as some of these tests do not seem to pass at -O0 using NVHPC 22.5. See: https://github.com/BlueBrain/CoreNeuron/pull/841#issuecomment-1181523812.
Also update NMODL to the latest `master`, which now requires Python 3.7+.
Build CoreNEURON with tests enabled (and Boost), run the `test-solver` test. Or just execute …

Add unit tests for the Hines solver.

---

extra/nrnivmodl_core_makefile.in

Needed for neuronsimulator/nrn#1939
CI_BRANCHES:NEURON_BRANCH=fixmf

nrnivmodl_core_makefile: fix SDKROOT

---

tests/CMakeLists.txt

https://github.com/BlueBrain/CoreNeuron/pull/841 added tests that use a two-parameter form of the `BOOST_AUTO_TEST_CASE` macro, which was added in https://github.com/boostorg/test/commit/24e5ddec4a0100d0f9464b9ecfe3d4a658ee96fe and exists in Boost 1.59+.
This is causing failures on CentOS7 in https://github.com/neuronsimulator/nrn-build-ci/runs/7738697401 after the NEURON submodule of CoreNEURON was updated in https://github.com/neuronsimulator/nrn/pull/1942.

Minimum Boost 1.59

---

.bbp-project.yaml
.github/workflows/clang_cmake_format_check.yaml
.gitignore
CMake/packages/FindSphinx.cmake
CMake/packages/Findlikwid.cmake
CMake/packages/Findnmodl.cmake
CMake/packages/Findreportinglib.cmake
CMakeLists.txt

Usa last version of hpc-coding-conv

Use last hpc-coding-conventions formatter script

---

coreneuron/CMakeLists.txt

See https://github.com/neuronsimulator/nrn-build-ci/pull/51
Just to retrigger in a clean way - #854 

Link to libdl.so to avoid linking issues with mpich on centos7

---

coreneuron/CMakeLists.txt
extra/nrnivmodl_core_makefile.in

In the CI for neuronsimulator/nrn#1929 we started seeing errors like (https://github.com/neuronsimulator/nrn/runs/8186384877?check_suite_focus=true#step:8:939):
```
gmake[2]: *** No rule to make target 'bin/x86_64/libcorenrnmech.so', needed by 'bin/cmd_interface_test_bin'.  Stop.
```
which do not seem(?) to affect the builds using Ninja.
https://cmake.org/cmake/help/latest/command/add_custom_command.html mentions some restrictions on depending on the outputs of a custom command from other directories. These tweaks seem to avoid the issue.
Also, fix the `nrnivmodl-core` logic for when the `SDKROOT` environment variable is **not** set.

Try to declare dependencies on libcorenrnmech.so properly

---

coreneuron/network/multisend_setup.cpp

It seems that `i` is sometimes negative. In a debug build on macOS with AppleClang and AddressSanitizer this triggered an error in the `ring_gap_multisend_TEST` test. With this change the tests passed locally.
https://github.com/neuronsimulator/nrn/actions/runs/3054217216/jobs/4925838144#step:14:3620

Fix out-of-range error from ASan

---

coreneuron/utils/memory.h
coreneuron/utils/nrnoc_aux.cpp

Unfortunately aligned_alloc does not allow aligning buffers that are not a multiple of the alignment. To help with this we allocate slightly larger buffers where necessary.
Updates `alloc_memory` and `nrn_cacheline_alloc` to use `std::aligned_alloc` instead the POSIX memalign.
Fixes (partially) #836

Replace posix_memalign with std::aligned_alloc

---

.github/pull_request_template.md
coreneuron/CMakeLists.txt

* Cherry-pick #856 for future release 8.2.2
* To avoid CI errors like: https://github.com/neuronsimulator/nrn-build-ci/actions/runs/3125043801/jobs/5069877217#step:7:983
CI_BRANCHES:NEURON_BRANCH=release/8.2,NMODL_TAG=0.4,SPACK_BRANCH=develop

Cherry-pick for 8.2.1: Link to libdl.so to avoid linking issues with mpich on centos7 (#856)

---

coreneuron/io/mech_report.cpp

Print mechanism count and memory size only if count is >0. This helps reduce the verbosity of the output when `--model-stats` is enabled.
Example output from the following test is:
```
============== MECHANISMS COUNT AND SIZE BY TYPE =============
Id                 Name      Count   Total memory size (KiB)
3          capacitance        392                      7.91
4                  pas        372                     16.23
9               ExpSyn         40                      4.60
15               na_ion         20                      1.19
16                k_ion         20                      1.19
17                   hh         20                      4.70
18              NetStim          1                      0.21 …
```

Print mechanism count and memory size only if count is >0

---

coreneuron/io/output_spikes.cpp

MMB 70M cell simulation was failing when writing out.dat spikes.
This PR fixes the issue by changing the datatype of the number of spikes and the buffer size to unsigned long.
Jira ticket: https://bbpteam.epfl.ch/project/issues/browse/BBPBGLIB-941

Change num_spikes datatype to unsigned long

---

coreneuron/apps/main1.cpp
coreneuron/io/reports/binary_report_handler.cpp
coreneuron/io/reports/binary_report_handler.hpp
coreneuron/io/reports/nrnreport.hpp
coreneuron/io/reports/report_configuration_parser.cpp
coreneuron/io/reports/report_event.hpp
coreneuron/io/reports/report_handler.cpp
coreneuron/io/reports/report_handler.hpp
coreneuron/io/reports/sonata_report_handler.cpp
coreneuron/io/reports/sonata_report_handler.hpp

A high memory usage was taking place in the report initialization when reporting big targets.
**Solution**
Use a std::vector instead of a std::set to store the target gids and do the intersection between the target and the NrnThread gids to loop through them instead of searching in the full target.

Improve memory usage in report initialization

---

.github/workflows/coreneuron-ci.yml
.github/workflows/test-as-submodule.yml
CMake/packages/Findnmodl.cmake
README.md
coreneuron/apps/corenrn_parameters.cpp
coreneuron/apps/corenrn_parameters.hpp
coreneuron/apps/main1.cpp
coreneuron/io/mech_report.cpp
coreneuron/io/nrn_setup.cpp
coreneuron/io/nrn_setup.hpp
coreneuron/io/reports/binary_report_handler.cpp
coreneuron/io/reports/binary_report_handler.hpp
coreneuron/io/reports/nrnreport.hpp
coreneuron/io/reports/report_configuration_parser.cpp
coreneuron/io/reports/report_event.hpp
coreneuron/io/reports/report_handler.cpp
coreneuron/io/reports/report_handler.hpp
coreneuron/io/reports/sonata_report_handler.cpp
coreneuron/io/reports/sonata_report_handler.hpp
coreneuron/mechanism/mechanism.hpp

* Use a vector for the report target gids in order to save memory
* Add intersection function for the report gids
* Clean up target vector after initialization
* sync gids and compartment id types to sonata
CI_BRANCHES:NEURON_BRANCH=release/8.2,NMODL_BRANCH=release/8.2,SPACK_BRANCH=develop

Improve memory usage in report initialization (#882)
